### ISSUE TITLE
poppler 0.42 build error: 'isfinite' was not declared in this scope

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/legacy-linuxbrew#1015]
Error:

```
SplashOutputDev.cc: In member function 'virtual void SplashOutputDev::drawImageMask(GfxState*, Object*, Stream*, i
nt, int, GBool, GBool, GBool)':
SplashOutputDev.cc:2894:25: error: 'isfinite' was not declared in this scope
     if (!isfinite(ctm[i])) return;
                         ^
SplashOutputDev.cc:2894:25: note: suggested alternative:
In file included from /bio/linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/random:38:0,
                 from /bio/linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/bits/stl_algo.h:66,
                 from /bio/linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/algorithm:62,
                 from SplashOutputDev.cc:77:
/bio/linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/cmath:601:5: note:   'std::isfinite'
     isfinite(_Tp __x)
     ^
```
Logs: https://gist.github.com/facb9b4ab4bc3bf614432e4779250c26

Could be an upstream change that needs to be made to put ```std::`` namespace prefix?

I've filed it upstream: https://bugs.freedesktop.org/show_bug.cgi?id=94761

Build: xz ✔, pkg-config ✔
Required: cairo ✔, fontconfig ✔, freetype ✔, gettext ✔, glib ✔, gobject-introspection ✔, jpeg ✔, libpng ✔, libtiff ✔, openjpeg ✔
Optional: qt ✘, qt5 ✘, little-cms2 ✔

**Comment by sjackman** [comment]
Yeah, I'd guess it's an upstream bug related to GCC 5. It should be `std::isfinite`, as you noted.

**Comment by rwhogg** [comment]
FYI @tseemann the upstream developers responded to the bug, asking you to confirm if adding `std::` fixes it.

**Comment by rwhogg** [comment]
`poppler` was updated to version 0.47 and the upstream bug was marked "RESOLVED FIXED", so closing this.
