### ISSUE TITLE
libepoxy - configure: error: Package requirements (egl) were not met

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/legacy-linuxbrew#1027]
This is needed for `gtk+3`.
It works on OS X (with `--build-from-source`) but not on Linux:
I tried installing `gegl` package but that didn't seem to help either.
Logs: https://gist.github.com/d1e06cd0163c6e89850b01955c0bb669

```
brew install libepoxy
==> Downloading https://github.com/anholt/libepoxy/archive/v1.3.1.tar.gz
Already downloaded: /home/tseemann/.cache/Homebrew/libepoxy-1.3.1.tar.gz
==> Downloading http://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.0.tar.bz2
Already downloaded: /home/tseemann/.cache/Homebrew/libepoxy--xorg-macros-1.19.0.tar.bz2
==> ./configure --prefix=/tmp/libepoxy20160401-83307-u525vc/libepoxy-1.3.1/xorg-macros
==> make install
==> ./autogen.sh --disable-dependency-tracking --prefix=/bio/linuxbrew/Cellar/libepoxy/1.3.1
Last 15 lines from /home/tseemann/.cache/Homebrew/Logs/libepoxy/03.autogen.sh:
checking KHR/khrplatform.h usability... yes
checking KHR/khrplatform.h presence... yes
checking for KHR/khrplatform.h... yes
checking if /bio/linuxbrew/bin/gcc-5 supports -Wno-int-conversion... yes
checking for EGL... no
configure: error: Package requirements (egl) were not met:

No package 'egl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables EGL_CFLAGS
and EGL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by DoomHammer** [comment]
This looks like a part of Mesa so I would bet it should be a part of `linuxbrew/xorg/xorg`. What's your  opinion @rwhogg @maxim-belkin ?

**Comment by rwhogg** [comment]
I think it's a reasonable fit for `homebrew-xorg`

**Comment by maxim-belkin** [comment]
I think it should end up in another tap that would depend on linuxbrew/xorg. It will follow once linuxbrew/xorg is more or less finalized (currently, the only issue is documentation, but otherwise it is pretty usable).

**Comment by sjackman** [comment]
Is the `mesalib-glw` formula related? https://github.com/Homebrew/homebrew-x11/blob/master/mesalib-glw.rb

**Comment by rwhogg** [comment]
`mesalib-glw` only installs `libGLw` and assorted header files.

There's a Debian package named `libegl1-mesa` which comes from the source package `mesa`, as described [here](http://packages.ubuntu.com/source/trusty/mesa). By contrast, `libglw-mesa` - basically some X/Athena widgets - comes from the source package [`glw`](http://packages.ubuntu.com/source/trusty/glw). So I think the answer is: `mesalib-glw` is definitely related, but not the same.

I haven't had the time to dig into it properly, but based on an interactive install of `mesalib-glw`, I'm going to guess that EGL isn't part of the tarball.

**Comment by sjackman** [comment]
Does it make any sense to have `mesa` on Mac, or is it a Linux-only formula? I'd suggest putting it in `linuxbrew/xorg` if it's Linux only and `homebrew/x11` if it's portable to both OS.

**Comment by romainstuder** [comment]
Any update for this problem? I am facing exactly the same trouble.

**Comment by sjackman** [comment]
Afraid not, other than the possibility of creating a Linuxbrew formula for MESA. You can install X.Org like so `linuxbrew/xorg/xorg`, but it doesn't yet include OpenGL.

**Comment by DoomHammer** [comment]
@rwhogg @maxim-belkin how do you see it?

**Comment by rwhogg** [comment]
@maxim-belkin recently created a `mesa` formula; it should now be available by running `brew install linuxbrew/xorg/mesa`.

We'll eventually have to start making it a requirement for some of the existing formulae.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#937
