### ISSUE TITLE
vim: error: EXTERN.h: No such file or directory

### ISSUE THREAD

**Issue by dragonxlwang** [Linuxbrew/legacy-linuxbrew#1046]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

[gist](https://gist.github.com/aa15a009cb299ae2a58806de1a37dfca)

**Comment by rwhogg** [comment]
From https://gist.github.com/dragonxlwang/aa15a009cb299ae2a58806de1a37dfca#file-02-make-L2-L149

> if_perl.xs:58:20: fatal error: EXTERN.h: No such file or directory

Now that you installed `perl` from #1047, does this problem still occur?

**Comment by dragonxlwang** [comment]
yes, It fails unless I use basic install without any addon...

**Comment by sjackman** [comment]
Please report `brew list perl | grep EXTERN.h`

e.g.
```
$ brew list perl |grep EXTERN.h
/gsc/btl/linuxbrew/Cellar/perl/5.22.1/lib/5.22.1/x86_64-linux-thread-multi/CORE/EXTERN.h
```

**Comment by sjackman** [comment]
https://gist.github.com/dragonxlwang/aa15a009cb299ae2a58806de1a37dfca#file-00-config-out-L0-L20
`Perl: /usr/bin/perl`
I don't believe you have `perl` installed with Linuxbrew.

**Comment by dragonxlwang** [comment]
Sorry for late reply.

But I do have brew perl:

```
$ ~/.linuxbrew/bin/perl --version

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-thread-multi

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by sjackman** [comment]
Perhaps that gist is out of date. Please report `brew install vim; brew gist-logs vim`

**Comment by lparsons** [comment]
I'm running into the same issue: output from `brew install vim; brew gist-logs vim`: https://gist.github.com/8f19eb13e2f018823bef377f0f24c72e

**Comment by sjackman** [comment]
```
if_perl.xs:57:20: fatal error: EXTERN.h: No such file or directory
```
https://gist.github.com/anonymous/8f19eb13e2f018823bef377f0f24c72e#file-02-make-L123

**Comment by sjackman** [comment]
```
Perl: /usr/local/bin/perl => /usr/bin/perl
```
https://gist.github.com/anonymous/8f19eb13e2f018823bef377f0f24c72e#file-00-config-out-L16

Do you have `perl` installed using Linuxbrew? Please report
```sh
brew list --versions perl
which -a perl
```

**Comment by lparsons** [comment]
Installing perl ran into a separate issue (though perhaps I can just force install and ignore the test error?). `brew install perl; brew gist-logs perl`: https://gist.github.com/anonymous/c857358d39db38cb1472356d2816d28d

I'm installing this as a non-root user (with no root privs) so there is no `linuxbrew` user and thus installing it into `${HOME}/.linuxbrew`.

**Comment by sjackman** [comment]
```
t/op/groups ................................................... FAILED--expected test 1, saw test 2
Failed 1 test out of 2321, 99.96% okay.
	op/groups.t
```
https://gist.github.com/anonymous/c857358d39db38cb1472356d2816d28d#file-03-make-L808

I'd suggest reporting that bug upstream to the PERL developers. Try
```sh
brew install perl --without-test
```

**Comment by lparsons** [comment]
OK, was able to get perl installed using the `--without-test` flags.  However, vim install ended up with the same error: https://gist.github.com/34b11720a23190d2e73da5d91ae201da

**Comment by sjackman** [comment]
Shucks. Perhaps `vim` needs a `configure` option to specify the location of the `perl` header files. Are you able to look into that?

**Comment by lparsons** [comment]
Will see what I can do, but not really. I've built it from source myself, just thought it would be handy to have linuxbrew do it (manage updates, etc.). I'll poke around, but so far, I've not found much.

I do see the file in a couple of places in `.linuxbrew`:

```
:~/.linuxbrew$ find . -name "EXTERN.h"
./Cellar/perl/5.24.0_2/lib/perl5/5.24.0/x86_64-linux-thread-multi/CORE/EXTERN.h
./lib/perl5/5.24.0/x86_64-linux-thread-multi/CORE/EXTERN.h
```

**Comment by sjackman** [comment]
As a hack workaround adding the following (untested) to the formula may help:
```ruby
ENV["C_INCLUDE_PATH"] = Formula["perl"].lib/"perl5/5.24.0/x86_64-linux-thread-multi/CORE"
```

**Comment by cambxh** [comment]
I met this error under CentOS 7 and solved with "yum -y install perl-devel perl-ExtUtils-Embed" before making

**Comment by sjackman** [comment]
Thanks for the workaround, @cambxh.

**Comment by sjackman** [comment]
@cambxh Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `vim`.

**Comment by M0bil3Rulz** [comment]
On Centos, I resolved by adding CFLAGS onto "**./configure**" command.

`$ locate EXTERN.h`
/usr/lib64/perl5/CORE/EXTERN.h

`$ CFLAGS="-I/usr/lib64/perl5/CORE/" ./configure --prefix=/opt/vim ...`

(where `...` is other options you want configured during compilation)
