### ISSUE TITLE
perl install fails

### ISSUE THREAD

**Issue by dragonxlwang** [Linuxbrew/legacy-linuxbrew#1047]
Here's the [gist](https://gist.github.com/dragonxlwang/34ab6758653063117dcfde01983a0ebc)

seems related to #186.

Test fails: groups.t 

And a post about this: https://rt.perl.org/Public/Bug/Display.html?id=116775

**Comment by rwhogg** [comment]
The error looks like it comes from `make test` and is at https://gist.github.com/dragonxlwang/34ab6758653063117dcfde01983a0ebc#file-03-make-L3-L827

@dragonxlwang, as a workaround until the upstream bug is fixed, you can try `brew edit perl` and comment out the `make test`.

**Comment by dragonxlwang** [comment]
I used the option without test to build it — hope it won’t cause too much trouble later.

**Comment by sjackman** [comment]
Thanks for the bug report.

https://gist.github.com/dragonxlwang/34ab6758653063117dcfde01983a0ebc#file-03-make-L3-L827
```
t/op/groups ................................................... FAILED--expected test 1, saw test 2
```

Can you get more info from this particular failure?

```
Failed 1 test out of 2296, 99.96% okay.
	op/groups.t
### Since not all tests were successful, you may want to run some of
### them individually and examine any diagnostic messages they produce.
### See the INSTALL document's section on "make test".
### You have a good chance to get more information by running
###   ./perl harness
### in the 't' directory since most (>=80%) of the tests succeeded.
### You may have to set your dynamic library search path,
### LD_LIBRARY_PATH, to point to the build directory:
###   setenv LD_LIBRARY_PATH `pwd`:$LD_LIBRARY_PATH; cd t; ./perl harness
###   LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd t; ./perl harness
###   export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH; cd t; ./perl harness
### for csh-style shells, like tcsh; or for traditional/modern
### Bourne-style shells, like bash, ksh, and zsh, respectively.
```

**Comment by dragonxlwang** [comment]
as @rwhogg said, I also believe this is likely not a problem of brew, but with upstream perl.

**Comment by sjackman** [comment]
Okay.
