### ISSUE TITLE
ncurses: configure: error: Cannot link with GPM library

### ISSUE THREAD

**Issue by bsmith89** [Linuxbrew/legacy-linuxbrew#1081]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

`ncurses` is required for many packages, but `brew install ncurses` fails with the following:

```
Last 15 lines from /home/bjsm/.cache/Homebrew/Logs/ncurses/01.configure:
checking if you want to build shared libraries... yes
checking if you want to build static libraries... yes
checking if you want to build debug libraries... yes
checking if you want to build profiling libraries... no
checking if you want to build C++ shared libraries... no
checking for specified models...  shared normal debug
checking for default model... shared
checking if you want to have a library-prefix... auto
checking for PATH separator... :
checking if you want to build a separate terminfo library... no
checking if you want to build a separate tic library... no
checking if you want to link with the GPM mouse library... maybe
checking for gpm.h... yes
checking for Gpm_Open in -lgpm... no
configure: error: Cannot link with GPM library

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-dupes/issues

These open issues may also help:
Fish: depends on ncurses https://github.com/Linuxbrew/linuxbrew/pull/1080
Fish depends on ncurses https://github.com/Linuxbrew/linuxbrew/issues/1079
```

`libgpm` itself requires `ncurses`, so `brew install libgpm` doesn't help.

gist-logs link:
https://gist.github.com/86e900649aeb67b561041639bda39c39.

**Comment by sjackman** [comment]
Wow, a circular dependency between `ncurses` and `libgpm`? That's not fun at all. Really not. For weird situations like this *Linux From Scratch* usually has helpful information. Off the top of my head, I'd suggest trying adding an option like `--without-gpm` (you'll have to check its exact name with `./configure --help`) to the `configure` command of `ncurses`.

**Comment by bsmith89** [comment]
`--without-gpm` appears to be the correct flag, but `brew install ncurses --without-gpm` fails with the same error.

It would appear that that flag is not being passed through to the `configure` script.

**Comment by bsmith89** [comment]
I _am_ able to build and install ncurses myself with the `--without-gpm` flag.

**Comment by bsmith89** [comment]
I was able to solve my issue by adding that flag directly to the formula.  I am curious why the flag wasn't being passed through, though.

**Comment by sjackman** [comment]
You do have to add the flag to the formula. There's no automatic passing of `brew` command line arguments to the `configure` command. Please submit a pull request.
