### ISSUE TITLE
Please have a look

### ISSUE THREAD

**Issue by Swapnil2095** [Linuxbrew/legacy-linuxbrew#1113]
```
swapnil@Gravity:~/Documents/CS422/4$ brew install pandoc
Error: undefined method `rebuild' for #<BottleSpecification:0x00000001967a48>
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/swapnil/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:9:in `block in <class:Ghc>'
/home/swapnil/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/home/swapnil/.linuxbrew/Library/Homebrew/software_spec.rb:91:in `bottle'
/home/swapnil/.linuxbrew/Library/Homebrew/formula.rb:1729:in `bottle'
/home/swapnil/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:7:in `<class:Ghc>'
/home/swapnil/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:1:in `load_formula'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/swapnil/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/swapnil/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/home/swapnil/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
/home/swapnil/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/swapnil/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
/home/swapnil/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
/home/swapnil/.linuxbrew/Library/Homebrew/formula.rb:1223:in `recursive_dependencies'
/home/swapnil/.linuxbrew/Library/Homebrew/requirement.rb:196:in `expand'
/home/swapnil/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
/home/swapnil/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
/home/swapnil/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
/home/swapnil/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
/home/swapnil/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
/home/swapnil/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
/home/swapnil/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
/home/swapnil/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
/home/swapnil/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
/home/swapnil/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by sjackman** [comment]
> `Error: undefined method 'rebuild'`

Try `brew update`

`ghc` hasn't been building correctly. A workaround is to install GHC 7.10.3b like so:
```sh
brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/6e4d8edba1f5d3a1aa796559d9bc3d7bdf1024cd/Formula/ghc.rb
brew install pandoc
```

**Comment by Swapnil2095** [comment]
$ brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/6e4d8edba1f5d3a1aa796559d9bc3d7bdf1024cd/Formula/ghc.rb
######################################################################## 100.0%
==> Tapping homebrew/dupes
Cloning into '/home/swapnil/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Tapped 38 formulae (103 files, 324.7K)
==> Installing dependencies for ghc: patchelf, pkg-config, homebrew/dupes/ncurses
==> Installing ghc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
/home/swapnil/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2M
==> Installing ghc dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/swapnil/.linuxbrew/Cellar/pkg-config/0.29.1_2 --disable-host-tool --with-internal
==> make
==> make check
==> make install
/home/swapnil/.linuxbrew/Cellar/pkg-config/0.29.1_2: 10 files, 672.5K, built in 36 seconds
==> Installing ghc dependency: homebrew/dupes/ncurses
==> Downloading https://ftpmirror.gnu.org/ncurses/ncurses-6.0.tar.gz
==> Downloading from http://gnumirror.nkn.in/ncurses/ncurses-6.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/swapnil/.linuxbrew/Cellar/ncurses/6.0_2 --enable-pc-files --with-pkg-config-libdi

==> make
Last 15 lines from /home/swapnil/.cache/Homebrew/Logs/ncurses/02.make:
 ^
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o demo_panels ../obj_s/demo_panels.o -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -L../lib -lformw -lmenuw -lpanelw -lncursesw    -lutil -lm
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o demo_termcap ../obj_s/demo_termcap.o -L../lib -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -lncursesw   -lutil -lm
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o demo_terminfo ../obj_s/demo_terminfo.o -L../lib -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -lncursesw   -lutil -lm
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o ditto ../obj_s/ditto.o -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  `echo "-L../lib -lformw -lmenuw -lpanelw -lncursesw   " | sed -e 's/-lform.*-lpanel[^ ]*//'` -lutil -lm 
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o dots ../obj_s/dots.o -L../lib -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -lncursesw   -lutil -lm
Makefile:808: recipe for target '../obj_s/ncurses.o' failed
make[1]: *** [../obj_s/ncurses.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/test'
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-dupes/issues

/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:31:in `open'
	from /home/swapnil/.linuxbrew/Library/Homebrew/utils.rb:621:in `open'
	from /home/swapnil/.linuxbrew/Library/Homebrew/utils.rb:654:in `issues_matching'
	from /home/swapnil/.linuxbrew/Library/Homebrew/utils.rb:686:in `issues_for_formula'
	from /home/swapnil/.linuxbrew/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /home/swapnil/.linuxbrew/Library/Homebrew/exceptions.rb:218:in `issues'
	from /home/swapnil/.linuxbrew/Library/Homebrew/exceptions.rb:263:in `dump'
	from /home/swapnil/.linuxbrew/Library/brew.rb:133:in `rescue in <main>'
	from /home/swapnil/.linuxbrew/Library/brew.rb:29:in `<main>'

**Comment by sjackman** [comment]
Looks like GCC crashed, which may be tricky to troubleshoot. Please report
```sh
brew gist-logs ncurses
```

You may try
```
brew install gcc ncurses
```

**Comment by Swapnil2095** [comment]
$ brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/6e4d8edba1f5d3a1aa796559d9bc3d7bdf1024cd/Formula/ghc.rb
######################################################################## 100.0%
==> Tapping homebrew/dupes
Cloning into '/home/swapnil/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Tapped 38 formulae (103 files, 324.7K)
==> Installing dependencies for ghc: patchelf, pkg-config, homebrew/dupes/ncurses
==> Installing ghc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
/home/swapnil/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2M
==> Installing ghc dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/swapnil/.linuxbrew/Cellar/pkg-config/0.29.1_2 --disable-host-tool --with-internal
==> make
==> make check
==> make install
/home/swapnil/.linuxbrew/Cellar/pkg-config/0.29.1_2: 10 files, 672.5K, built in 36 seconds
==> Installing ghc dependency: homebrew/dupes/ncurses
==> Downloading https://ftpmirror.gnu.org/ncurses/ncurses-6.0.tar.gz
==> Downloading from http://gnumirror.nkn.in/ncurses/ncurses-6.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/swapnil/.linuxbrew/Cellar/ncurses/6.0_2 --enable-pc-files --with-pkg-config-libdi

==> make
Last 15 lines from /home/swapnil/.cache/Homebrew/Logs/ncurses/02.make:
 ^
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o demo_panels ../obj_s/demo_panels.o -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -L../lib -lformw -lmenuw -lpanelw -lncursesw    -lutil -lm
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o demo_termcap ../obj_s/demo_termcap.o -L../lib -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -lncursesw   -lutil -lm
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o demo_terminfo ../obj_s/demo_terminfo.o -L../lib -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -lncursesw   -lutil -lm
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o ditto ../obj_s/ditto.o -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  `echo "-L../lib -lformw -lmenuw -lpanelw -lncursesw   " | sed -e 's/-lform.*-lpanel[^ ]*//'` -lutil -lm 
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
/usr/bin/gcc-5 -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -o dots ../obj_s/dots.o -L../lib -Wl,-rpath,/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/lib  -L/home/swapnil/.linuxbrew/lib -Wl,--dynamic-linker=/home/swapnil/.linuxbrew/lib/ld.so -Wl,-rpath,/home/swapnil/.linuxbrew/lib -I. -I. -I../test -DHAVE_CONFIG_H -I. -I../include -isystem/home/swapnil/.linuxbrew/include -P -D_GNU_SOURCE -DNDEBUG -Os -w -pipe -march=core2  --param max-inline-insns-single=1200  -fPIC  -lncursesw   -lutil -lm
Makefile:808: recipe for target '../obj_s/ncurses.o' failed
make[1]: *** [../obj_s/ncurses.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/ncurses20161104-25504-1fyxhho/ncurses-6.0/test'
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-dupes/issues

/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:31:in `open'
	from /home/swapnil/.linuxbrew/Library/Homebrew/utils.rb:621:in `open'
	from /home/swapnil/.linuxbrew/Library/Homebrew/utils.rb:654:in `issues_matching'
	from /home/swapnil/.linuxbrew/Library/Homebrew/utils.rb:686:in `issues_for_formula'
	from /home/swapnil/.linuxbrew/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /home/swapnil/.linuxbrew/Library/Homebrew/exceptions.rb:218:in `issues'
	from /home/swapnil/.linuxbrew/Library/Homebrew/exceptions.rb:263:in `dump'
	from /home/swapnil/.linuxbrew/Library/brew.rb:133:in `rescue in <main>'
	from /home/swapnil/.linuxbrew/Library/brew.rb:29:in `<main>'

**Comment by Swapnil2095** [comment]
swapnil@Gravity:~/Documents/CS422/4$ brew install pandoc
==> Installing dependencies for pandoc: ghc, gpatch, cabal-install
==> Installing pandoc dependency: ghc
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz
Already downloaded: /home/swapnil/.cache/Homebrew/ghc-8.0.1.tar.xz
==> Downloading https://ftpmirror.gnu.org/gmp/gmp-6.1.0.tar.bz2
Already downloaded: /home/swapnil/.cache/Homebrew/ghc--gmp-6.1.0.tar.bz2
==> ./configure --prefix=/home/swapnil/.linuxbrew/Cellar/ghc/8.0.1/libexec/integer-gmp --with-pic --disable-shar
==> make
==> make check
 ==> make install
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-apple-darwin.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/tmp/ghc-20161104-8373-19ewf57/ghc-8.0.1/binary --with-gmp-includes=/home/swapnil/.linu
Last 15 lines from /home/swapnil/.cache/Homebrew/Logs/ghc/05.configure:
2016-11-04 20:06:18 +0530

./configure
--prefix=/tmp/ghc-20161104-8373-19ewf57/ghc-8.0.1/binary
--with-gmp-includes=/home/swapnil/.linuxbrew/Cellar/ghc/8.0.1/libexec/integer-gmp/include
--with-gmp-libraries=/home/swapnil/.linuxbrew/Cellar/ghc/8.0.1/libexec/integer-gmp/lib
--with-ld=ld
--with-gcc=gcc

checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: 12: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: Syntax error: Unterminated quoted string
configure: error: cannot determine current directory

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues

These open issues may also help:
ghc: apply 10.12 dynlibdir patch directly to 8.0.1 https://github.com/Homebrew/homebrew-core/pull/6416
swapnil@Gravity:~/Documents/CS422/4$  ~

**Comment by sjackman** [comment]
Looks like GCC crashed, which may be tricky to troubleshoot. Please report
```sh
brew gist-logs ncurses
```

You may try
```
brew install gcc ncurses
```
