### ISSUE TITLE
Error: Failed to download resource "util-linux"

### ISSUE THREAD

**Issue by Muflone82** [Linuxbrew/legacy-linuxbrew#1114]
I all,

i'm trying to install "util-linux" but brew can't download it.

```
curl: (35) Cannot communicate securely with peer: no common encryption algorithm(s).
Error: Failed to download resource "util-linux"
Download failed: https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz
```

I tried with the command:
```
brew fetch util-linux
```
but I had the same answer

```
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-lin

curl: (35) Cannot communicate securely with peer: no common encryption algorithm(s).
Error: Failed to download resource "util-linux"
Download failed: https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz
```

Can yuo help me?
Thx

**Comment by maxim-belkin** [comment]
> Can yuo help me?
Thx

While we are waiting for yuo to help you out, I was wondering if you could run the following code and post the results here
```
brew update && cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
brew doctor
```

**Comment by sjackman** [comment]
Also try
```sh
curl -k -o `brew --cache -s curl` https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-linux-2.27.1.tar.xz
brew fetch curl
```

**Comment by Muflone82** [comment]
I ran
`brew` update && cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update``

and the result was
`Already` up-to-date.
remote: Counting objects: 229, done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 229 (delta 116), reused 229 (delta 116), pack-reused 0
Receiving objects: 100% (229/229), 137.23 KiB | 101.00 KiB/s, done.
Resolving deltas: 100% (116/116), done.
From https://github.com/Linuxbrew/brew
 * [new branch]      gh-pages   -> origin/gh-pages
HEAD is now at b75ca7b CONTRIBUTING.md: Update Contributing to Linuxbrew
Already up-to-date.``

then I tried to run again
`brew install util-linux`
This time I downloaded the module but didn't work the installation :-(

`==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.27/util-lin
Already downloaded: /home/marcelletti/.cache/Homebrew/util-linux-2.27.1.tar.xz
==> ./configure --disable-silent-rules --prefix=/home/marcelletti/.linuxbrew/Cellar/util-linux/2.27.1_1 --disable-use-tty-group --disable-kill --disab
==> make install
Last 15 lines from /home/marcelletti/.cache/Homebrew/Logs/util-linux/02.make:
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/tmp/util-linux-20161110-24695-tl5fbu/util-linux-2.27.1'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/tmp/util-linux-20161110-24695-tl5fbu/util-linux-2.27.1'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/util-linux-20161110-24695-tl5fbu/util-linux-2.27.1'
make: *** [install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues`


`curl-7.50.3` already installed``

**Comment by maxim-belkin** [comment]
what do you get if you do: `cd $(brew --repo) && git remote -v && brew tap`?

**Comment by Muflone82** [comment]
`origin https://github.com/Linuxbrew/brew (fetch)
origin https://github.com/Linuxbrew/brew (push)
homebrew/dupes
homebrew/core
homebrew/science`

**Comment by maxim-belkin** [comment]
`brew gist-logs util-linux` and post the url here.

**Comment by Muflone82** [comment]
The url is:

https://gist.github.com/11cf8582439d2db7109b47e746ff5c0b

**Comment by maxim-belkin** [comment]
So, your problem is:
```makefile
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/blkid’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/col’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/colcrt’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/colrm’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/column’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/findmnt’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/flock’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/getopt’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/hexdump’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/ipcrm’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/ipcs’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/isosize’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/logger’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/look’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/share/bash-completion/completions/lsipc’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/mcookie’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/mkfs’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/mkswap’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/namei’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/prlimit’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/readprofile’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/renice’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/rev’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/script’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/scriptreplay’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/setsid’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/tailf’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/whereis’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/wipefs’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/fsck’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/share/bash-completion/completions/mkfs.bfs’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/fsck.minix’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/mkfs.minix’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/fsck.cramfs’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/mkfs.cramfs’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/addpart’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/delpart’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/resizepart’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/partx’: Permission denied
/usr/bin/install: cannot remove ‘/usr/share/bash-completion/completions/raw’: Permission denied
```

**Comment by maxim-belkin** [comment]
please report the result of:
```bash
direct=""
for dir in $(echo "/usr/share/bash-completion/completions" | tr "/" " "); do
    direct="$direct/$dir";
    [ ! -d "$direct" ] || ls -led $direct;
done
```

**Comment by maxim-belkin** [comment]
Also, you can safely remove Debian's `snp-sites` because:
```
$ brew desc -s snp
parsnp: Microbial core genome alignment and SNP detection
snp-sites: Find SNP sites in a multi FASTA alignment file
snpeff: Genetic variant annotation and effect prediction toolbox
```

**Comment by Muflone82** [comment]
Why permission denied? Must I be root to run this?

Result is:

`ls: invalid option -- 'e'
Try 'ls --help' for more information.
ls: invalid option -- 'e'
Try 'ls --help' for more information.
ls: invalid option -- 'e'
Try 'ls --help' for more information.
ls: invalid option -- 'e'
Try 'ls --help' for more `information.`

**Comment by maxim-belkin** [comment]
no, just remote `e` from `ls -led`. Basically, run:
```bash
direct=""
for dir in $(echo "/usr/share/bash-completion/completions" | tr "/" " "); do
    direct="$direct/$dir";
    [ ! -d "$direct" ] || ls -ld $direct;
done
```

**Comment by Muflone82** [comment]
`drwxr-xr-x. 12 root root 4096 Dec 12  2013 /usr
drwxr-xr-x. 296 root root 12288 Nov  9 13:24 /usr/share
drwxr-xr-x. 4 root root 4096 Nov 11  2014 /usr/share/bash-completion
drwxr-xr-x. 2 root root 20480 Nov  8 13:27 /usr/share/bash-completion/completions`

Grazie :-)

**Comment by Muflone82** [comment]
Must I change the permission of the dir /usr/share/bash-completion?

`chmod -R 777 /usr/share/bash-completion`   ?

**Comment by maxim-belkin** [comment]
> Must I change the permission of the dir /usr/share/bash-completion?

no, you must not. Give us some time to figure out what is going on.

**Comment by maxim-belkin** [comment]
Problems:
```make
Bash completions:  /usr/share/bash-completion/completions
Systemd support:   no
...
Package tinfo was not found in the pkg-config search path
Package libuser was not found in the pkg-config search path
Package libsystemd was not found in the pkg-config search path
Package libsystemd-daemon was not found in the pkg-config search path
Package libsystemd-journal was not found in the pkg-config search path
Package python-2.7 was not found in the pkg-config search path
```

**Comment by maxim-belkin** [comment]
In my installation, I've got:
```
Bash completions:  ${datarootdir}/bash-completion/completions
Systemd support:   yes
```

**Comment by maxim-belkin** [comment]
Can you post the result of the following two commands?
```
type -a pkg-config
pkg-config --variable=completionsdir bash-completion
```

**Comment by maxim-belkin** [comment]
can you remove `bash-completion` that was installed with `apt-get`?

**Comment by Muflone82** [comment]
> 
Can you post the result of the following two commands?
type -a pkg-config
pkg-config --variable=completionsdir bash-completion
> 

`type -a pkg-config`
pkg-config is /home/marcelletti/.linuxbrew/bin/pkg-config
pkg-config is /home/marcelletti/.linuxbrew/bin/pkg-config
pkg-config is /usr/bin/pkg-config
pkg-config is /bin/pkg-config

`pkg-config --variable=completionsdir bash-completion`
/usr/share/bash-completion/completions

**Comment by Muflone82** [comment]
> can you remove bash-completion that was installed with apt-get?

Yes, I can; I installed `bash-completion` with `yum` because I have Fedora.
If I remove `bash-completion` I will have a problem with another software?

**Comment by maxim-belkin** [comment]
No, you won't have any problems. Just no bash-completions.
What happens is the following: 
During the installation of `util-linux`, `pkg-config` tries to determine if package `bash-completions` is installed. This is so in your case, but the location where `bash-completions` is installed is not writable by you (you did `sudo yum install bash-completions`). Because of that, installation fails. I think we should think of a way to avoid this kind of error but for now the easiest solution is to remove `bash-completions` using `yum`.

**Comment by Muflone82** [comment]
Good morning :-)
Well, I have removed bash completion with yum and the I have installed util-linux without any problems!!!!

**Comment by malcook** [comment]
I am similarly afflicted while trying to install util-linux and wish not to remove system bash-completion.  Any hope for me?

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar
