### ISSUE TITLE
Unsupported special dependency: Perl

### ISSUE THREAD

**Issue by gaurav997** [Linuxbrew/legacy-linuxbrew#1122]
Error: Unsupported special dependency :perl
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/gg/.linuxbrew/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'

**Comment by sjackman** [comment]
You appear to be using a very old version of Linuxbrew. Please try installing a fresh copy of Linuxbrew using the installation instructions available at http://linuxbrew.sh
