### ISSUE TITLE
troubleshooting link is not working

### ISSUE THREAD

**Issue by mohamedRyanWilz** [Linuxbrew/legacy-linuxbrew#1123]
link here is not working 
https://github.com/Linuxbrew/legacy-linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by mohamedRyanWilz** [comment]
found it here
https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md

**Comment by sjackman** [comment]
Which web page or `brew` command pointed you to this old legacy Troubleshooting web page?
