### ISSUE TITLE
wiki: symlink by gfortran -dumpversion fails on centos 6.5

### ISSUE THREAD

**Issue by saqihel** [Linuxbrew/legacy-linuxbrew#156]
On my centos 6.5, gfortran -dumpverion outputs messy info while gcc is smart.

```
$ gcc -dumpversion
4.4.7
$ gfortran -dumpversion
GNU Fortran (GCC) 4.4.7 20120313 (Red Hat 4.4.7-4)
Copyright (C) 2010 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
```

So, following command on wiki fails to create a symlink.
https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc

```
$ ln -s `which gfortran` $prefix/bin/gfortran-`gfortran -dumpversion |cut -d. -f1,2`
ln: target `COPYING' is not a directory
```

This is not smart but it works.

```
$ ln -s `which gfortran` $prefix/bin/gfortran-`gfortran -dumpversion | head -n 1 | cut -d" " -f4 | cut -d. -f1,2`
```

**Comment by hbetts** [comment]
@saqihel the custom version of `dumpversion` in gfortran has been removed as of version 4.5 according to [GNU bug 41080](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41080).

Your workaround is sufficient in the short term (I'm actually using a similar approach for a RHEL box), but long-term the solution is to upgrade your operating system.

As of this writing, gfortran v4.8 is available in CentOS 7.

**Comment by sjackman** [comment]
In scientific computing we're often stuck with woefully out of date operating systems on our clusters, that admins refuse to upgrade. I'm on CentOS 5.10, for example, with GCC 4.4. That's the whole reason of being for Linuxbrew, to be able to install a modern toolchain and software on an old operating system.

**Comment by hbetts** [comment]
What would you suggest as a resolution to this issue? Would a note of the gfortran difference suffice? Request that, if `gfortran --version` reports earlier than 4.5, use such-and-such symlink approach, else use the other?

**Comment by sjackman** [comment]
Follow these instructions:
[To use GCC 4.4 on CentOS 5](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#to-use-gcc-44-on-centos-5)
