### ISSUE TITLE
git depends on curl

### ISSUE THREAD

**Issue by huahang** [Linuxbrew/legacy-linuxbrew#19]
/usr/bin/gcc -o http-fetch.o -c -MF ./.depend/http-fetch.o.d -MQ http-fetch.o -MMD -MP -isystem /home/huahang/.linuxbrew/include -Os -w -pipe -march=core2 -msse4 -I. -DNO_GETTEXT  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DXDL_FAST_HASH -DSHA1_HEADER='<openssl/sha.h>'  -DNO_STRLCPY -DNO_MKSTEMPS -DSHELL_PATH='"/bin/sh"'  http-fetch.c
/usr/bin/gcc -o credential-cache.o -c -MF ./.depend/credential-cache.o.d -MQ credential-cache.o -MMD -MP -isystem /home/huahang/.linuxbrew/include -Os -w -pipe -march=core2 -msse4 -I. -DNO_GETTEXT  -DHAVE_PATHS_H -DHAVE_DEV_TTY -DXDL_FAST_HASH -DSHA1_HEADER='<openssl/sha.h>'  -DNO_STRLCPY -DNO_MKSTEMPS -DSHELL_PATH='"/bin/sh"'  credential-cache.c
make: *** [http.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [http-walker.o] Error 1
In file included from http-fetch.c:3:0:
http.h:6:23: fatal error: curl/curl.h: No such file or directory
compilation terminated.

It seems it's a curl issue.

**Comment by netroby** [comment]
I have face the same issue , can it be auto resolve by brew? or at least print the help message help us out.

**Comment by sjackman** [comment]
The workaround is `brew insall git --with-brewed-curl`. Perhaps this should be the default.

**Comment by rwhogg** [comment]
Closing this since `--with-brewed-curl` is now the default.
