### ISSUE TITLE
Python 2.7.9 Compiles, but that's about it.

### ISSUE THREAD

**Issue by jlisic** [Linuxbrew/legacy-linuxbrew#215]
Hi, I am having some issues with Python.  Python itself will compile, but setup.py segfaults and checking the make logs, it appears that readline.h cannot be found.  This is quite odd since readline.h was installed through brew, and I have been able to compile some test programs against it with no issues.

I've tried forcing python.rb to find the include both through adding '-I' for readline to CFLAGS, but no luck.

[link to gist with logs](https://gist.github.com/jlisic/cc0a444baed0236cd67f)

```
==> Downloading https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz
Already downloaded: /home/lisijo/.cache/Homebrew/python-2.7.9.tgz
==> Downloading http://bugs.python.org/file30805/issue10910-workaround.txt
Already downloaded: /home/lisijo/.cache/Homebrew/python--patch-9926640cb7c8e273e4b451469a2b13d4b9df5ba3.txt
==> Patching
patching file Include/pyport.h
Hunk #1 succeeded at 713 (offset 14 lines).
Hunk #2 succeeded at 736 (offset 14 lines).
==> ./configure --prefix=/home/lisijo/.linuxbrew/Cellar/python/2.7.9 --enable-ipv6 --datarootdir=/home/lisijo/.linuxbrew/Cellar/python/2.7.9/share --datadir=/home/lisijo/.linuxbrew/Cellar/python/2.7.9/share --en
==> make
==> make install PYTHONAPPSDIR=/home/lisijo/.linuxbrew/Cellar/python/2.7.9
==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-8.0.tar.gz
Already downloaded: /home/lisijo/.cache/Homebrew/python--setuptools-8.0.tar.gz
==> Downloading https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz
Already downloaded: /home/lisijo/.cache/Homebrew/python--pip-1.5.6.tar.gz
==> Caveats
Setuptools and Pip have been installed. To update them
  pip install --upgrade setuptools
  pip install --upgrade pip

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /home/lisijo/.linuxbrew/lib/python2.7/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md
==> /home/lisijo/.linuxbrew/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install --force --verbose --install-scripts=/home/lisijo/.linuxbrew/Cellar/python/2.7.9/bin --install-lib=/home/lisijo/.linuxb
--verbose
--install-scripts=/home/lisijo/.linuxbrew/Cellar/python/2.7.9/bin
--install-lib=/home/lisijo/.linuxbrew/lib/python2.7/site-packages

/home/lisijo/.linuxbrew/Cellar/python/2.7.9/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
==> Summary
/home/lisijo/.linuxbrew/Cellar/python/2.7.9: 4934 files, 105M, built in 2.2 minutes
```

Starting python produces:

```
Python 2.7.9 (default, Dec 21 2014, 09:09:48)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/etc/pythonstart", line 7, in <module>
    import readline
ImportError: No module named readline
```

**Comment by bobobo1618** [comment]
I've been having issues here too. `setup.py` has a ton of `/usr/include/xxxx` hard coded into it and it wreaks havok all over the Python build. `ncurses` also seems to be a requirement for readline for some reason.

**Comment by bobobo1618** [comment]
Just to add to my previous comment, I built with debug and after the failure, replaced all the `/usr/xxx` in `setup.py` with their Homebrew equivalents and I now have an (apparently) working python installation.

The reason it seemed to break was that due to those hard coded paths, it used the system GCC standard headers (`stdio.h` etc.) rather than the Homebrew GCC headers.

I also added the `--oldinclude` switch to the configure script but I'm not sure if that affected anything. Even with it I had to replace the hard coded paths in `setup.py`.

**Comment by sjackman** [comment]
Patching `libexec/pip/setup.py` and `libexec/setuptools/setup.py` is an option.

**Comment by bobobo1618** [comment]
I'm referring to the Python source's `setup.py`, not the others. For example: https://github.com/python/cpython/blob/master/setup.py#L408

**Comment by sjackman** [comment]
Ah, I see. That's trickier to fix.

**Comment by iMichka** [comment]
This issue is pretty old. I'll close it. If you still have problems/questions with this, please open a new issue in our new repo: https://github.com/Linuxbrew/homebrew-core
