### ISSUE TITLE
ffmpeg fails to configure due to ongoing tmp folder issues

### ISSUE THREAD

**Issue by ylluminate** [Linuxbrew/legacy-linuxbrew#279]
After a bit of an issue with `pkg-config` where I had to repoint the tmp folder to the linuxbrew tmp folder, I ended up getting a problem with `ffmpeg` configuration:

```
╰─➤  brew install ffmpeg
==> Downloading https://www.ffmpeg.org/releases/ffmpeg-2.5.3.tar.bz2
Already downloaded: /home/admin/.cache/Homebrew/ffmpeg-2.5.3.tar.bz2
==> ./configure --prefix=/home/admin/.linuxbrew/Cellar/ffmpeg/2.5.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=/usr/bin/gcc --host-cflags=-Os -w -pipe -march=core2 --host-ldflags=-L/home/admin/.linu
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
Improve ffmpeg caveats regarding AAC (https://github.com/Homebrew/homebrew/pull/35876)
ffmpeg failed to build on 10.7.5 (https://github.com/Homebrew/homebrew/issues/34963)
gpac 0.5.0 doesn't build against ffmpeg 2.4.1 (https://github.com/Homebrew/homebrew/issues/32978)
```

After I found that the logging was in the OS X location and fixing it so that the logs are within the linuxbrew folder that makes more sense on Linux, I ended up seeing another issue where I believe that the HOMEBREW_TEMP folder may not be set properly in some cases.  In the `config.log` I see:

```
./configure: line 3143: /tmp/admin/ffconf.xtJP1qPn.sh: Permission denied
```

Is there another temp var that should be set since the HOMEBREW_TEMP (in this case the `linuxbrew/tmp` folder) is not being effective for configure?

**Comment by ylluminate** [comment]
So something is indeed causing this to want to use `/tmp` still instead of the tmp set via HOMEBREW_TEMP.  When I issued a `sudo mount -o remount,exec /tmp` and checked the mount points, it was fine and the compilation of `ffmpeg` proceeded without a hitch.

We need to figure out a way to make sure that we are able to use another tmp folder because using /tmp all the time without `noexec` is just not something I want to have continually running.  The other option might to be to run a check on compilation and warn the user to execute `mount -o remount,exec /tmp` or even execute that command for the user and then re-execute `mount -o remount,noexec /tmp` (or rather gather all of the options from fstab and execute the remount to get it back to its original settings).

**Comment by sjackman** [comment]
Does setting both `TMPDIR` and `HOMEBREW_TEMP` work?
