### ISSUE TITLE
tarsnap dependencies

### ISSUE THREAD

**Issue by usharf** [Linuxbrew/legacy-linuxbrew#286]
tar snaps needs this deps to compile on Debian/Ubuntu: libssl-dev, zlib1g-dev, and e2fslibs-dev, or glibc-devel, openssl-devel, zlib-devel,  e2fsprogs-devel RedHat/SUSE... 

source https://www.tarsnap.com/download.html

**Comment by sjackman** [comment]
Does `brew install openssl zlib` resolve your issue?
