### ISSUE TITLE
gnuplot: build fails to install LUA dependency (Linux only)

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/legacy-linuxbrew#354]
Works on OS X but not Linux:

https://github.com/Homebrew/homebrew/issues/38772

It seems to not be triggering the LUA dependency on Linux:

```
class LuaRequirement < Requirement
  fatal true
  default_formula "lua"
  satisfy { which "lua" }
end
```

**Comment by sjackman** [comment]
Hi, Torsten. I can't reproduced this issue. Can you confirm that it's still a problem for you?

```
$ brew reinstall gnuplot
==> Reinstalling gnuplot
==> Installing gnuplot dependency: lua
```

**Comment by sjackman** [comment]
Do you have lua installed somewhere in your PATH?
`which -a lua`

**Comment by tseemann** [comment]
The problem is that there is a system LUA installed. When I install the Brew LUA it goes in PATH first and gnuplot compiles. If I remove the Brew LUA, and just leave the system LUA, it fails.

```
which -a lua
/usr/bin/lua

==> Reinstalling gnuplot
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.0/gnuplot-5.0.0.tar.gz
Already downloaded: /home/tseemann/.cache/Homebrew/gnuplot-5.0.0.tar.gz
==> ./configure --disable-silent-rules --prefix=/bio/linuxbrew/Cellar/gnuplot/5.0.0 --with-readline=/bio/linuxbrew/opt/readline --with-gd=/bio/linuxbrew/opt/gd --disable-wxwidgets -
==> make
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/gnuplot20150426-83186-nyfc6w/gnuplot-5.0.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/gnuplot20150426-83186-nyfc6w/gnuplot-5.0.0'
make: *** [all] Error 2

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
gnuplot failed to build on 10.8.5 (https://github.com/Homebrew/homebrew/issues/37423)
```

But if i pre-install Brew LUA all is fine:

```
brew install lue
which -a lua
/bio/linuxbrew/bin/lua
/usr/bin/lua
brew reinstall gnuplot
==> Reinstalling gnuplot
/bio/linuxbrew/Cellar/gnuplot/5.0.0: 44 files, 2.4M, built in 29 seconds
```

This is a common theme I'm encountering during my new Brew career; lots of assumptions about system libraries, which is generally ok on OSX but not on Linux :(

**Comment by iggyvolz** [comment]
Could this be the same cause as #345?

**Comment by sjackman** [comment]
Yes, related. I suspect that the `LuaRequirement` is finding Lua in the path, but then the path is modified later during the build process so that it's no longer found, and the build fails.
