### ISSUE TITLE
How about adding pip to the requirements (apt/yum)

### ISSUE THREAD

**Issue by mscook** [Linuxbrew/legacy-linuxbrew#388]
Cmake fails if python setuptools are not present. 

Suggestion:

sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev

becomes -

sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev **python-pip**

and similarly for yum.

**Comment by iggyvolz** [comment]
Couldn't you just depends_on "python" unless OS.mac?

I'm not sure if that will handle the setuptools part and I'm not sure how linuxbrew can install setuptools for it.

**Comment by iggyvolz** [comment]
Err... adding python to dependencies for cmake is going to be interesting:
https://github.com/Homebrew/linuxbrew/blob/89a05340fe3b86dce3a1e8eb23f4dc730534d0eb/Library/Formula/cmake.rb#L17
```ruby
depends_on :python => :build if OS.mac? && MacOS.version <= :snow_leopard && build.with?("docs")
```
Merged from:
```ruby
depends_on :python => :build if MacOS.version <= :snow_leopard && build.with?("docs")
```

So I wonder if:
```ruby
depends_on :python => :build unless OS.mac? && MacOS.version <= :snow_leopard && build.with?("docs")
```
would solve that?

**Comment by mscook** [comment]
I'm a formula novice so I'm not sure.

**Comment by tdsmith** [comment]
To the limited extent that my opinion is useful:
* I don't know how linux distros package it, but pip is not setuptools. Homebrew/homebrew doesn't ever use pip but it assumes all pythons have setuptools installed
* It's possible to vendor setuptools if you want to modify PYTHONPATH at build time
* not building cmake's docs by default is a cromulent option
