### ISSUE TITLE
`cmake -E tar` is not working.

### ISSUE THREAD

**Issue by xu-cheng** [Linuxbrew/legacy-linuxbrew#391]
```
$ cmake -E tar xfz /tmp/chengxu/Caches/Homebrew/bison-3.0.4.tar.gz
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /tmp/chengxu/Caches/Homebrew/bison-3.0.4.tar.gz
```

I don't know but could it relate to #390?

**Comment by sjackman** [comment]
I definitely have this problem as well. Could be related? I'm not sure.

**Comment by sjackman** [comment]
I was hopeful, but unfortunately `TZ` is not the issue.

```
$ export TZ=:/etc/localtime
$ cmake -E tar xf /home/sjackman/.cache/Homebrew/hello-2.10.tar.gz
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /home/sjackman/.cache/Homebrew/hello-2.10.tar.gz
```

**Comment by sjackman** [comment]
I just ran into this issue again trying to compile `homebrew/science/salmon`. I'd sure love to fix it. See https://github.com/COMBINE-lab/salmon/issues/10

**Comment by sjackman** [comment]
My guess, and this is a long shot, is that it's a bug in the `tar` library of `cmake`, that's made evident because my system at work has up-to-date Linux headers and glibc but is running an eight-year-old Linux kernel (CentOS 5.10). I can upgrade everything with Linuxbrew except the running kernel. I've seen this situation show bugs before when the software uses compile time kernel feature checks like `HAVE_PIPE2` when it should be using a run time check, namely checking whether the call to `pipe2` fails with `ENOSYS`.

**Comment by rob-p** [comment]
Any update on this?  I can see it's still affecting @sjackman's ability to build `salmon` from source and I'm not able to repro the issue --- which is the worst kind of problem :disappointed: .

**Comment by sjackman** [comment]
No, I'm afraid there's been no progress. @xu-cheng Did you find a resolution to this issue?
@rob-p I'll see if I can reproduce it in a Docker image.

**Comment by sjackman** [comment]
> virtual memory exhausted: Cannot allocate memory

I was wondering when that would happen! It seems a `t2.micro` is too small to compile Salmon. =)

**Comment by jzee** [comment]
@sjackman - by any chance, is the filesystem you attempt to untar to FAT32?

**Comment by sjackman** [comment]
Alas, no, it's `ext3`.

**Comment by sjackman** [comment]
I think this issue may be related to the kernel version. The exact same `cmake` executable from the bottle `cmake-3.4.3.x86_64_linux.bottle.tar.gz` works on CentOS 6.6 with Linux 2.6.32, but does not work on CentOS 5.11 with Linux 2.6.18. This is the same installation of standaloneLinuxbrew, so exact same libraries and everything else.

**Comment by sjackman** [comment]
Can anyone else experiencing this issue please report your distribution and kernel version? `brew config`

**Comment by sjackman** [comment]
I believe this issue's root cause is an upstream `cmake` bug related to building with a newer set of Linux kernel headers and running on an older kernel.
