### ISSUE TITLE
gdb is not working

### ISSUE THREAD

**Issue by xu-cheng** [Linuxbrew/legacy-linuxbrew#400]
This gdb is installed by `brew install homebrew/dupes/gdb --with-brewed-python`. It built fine. But when I run it, it shows:

```
$ gdb
Cannot create pipe for readline
```

The gdb is indeed linked to readline:

```
 $ ldd $(which gdb)
    linux-vdso.so.1 (0x00007ffffc0e4000)
    libreadline.so.6 => /home/comp/chengxu/usr/lib/libreadline.so.6 (0x00002b491b7df000)
    libdl.so.2 => /home/comp/chengxu/usr/lib/libdl.so.2 (0x00002b491ba24000)
    libncursesw.so.5 => /home/comp/chengxu/usr/lib/libncursesw.so.5 (0x00002b491bc28000)
    libz.so.1 => /home/comp/chengxu/usr/lib/libz.so.1 (0x00002b491be74000)
    libm.so.6 => /home/comp/chengxu/usr/lib/libm.so.6 (0x00002b491c086000)
    libpthread.so.0 => /home/comp/chengxu/usr/lib/libpthread.so.0 (0x00002b491c378000)
    libutil.so.1 => /home/comp/chengxu/usr/lib/libutil.so.1 (0x00002b491c596000)
    libpython2.7.so.1.0 => /home/comp/chengxu/usr/lib/libpython2.7.so.1.0 (0x00002b491c799000)
    libexpat.so.1 => /home/comp/chengxu/usr/lib/libexpat.so.1 (0x00002b491cb9f000)
    liblzma.so.5 => /home/comp/chengxu/usr/lib/liblzma.so.5 (0x00002b491cdbf000)
    libc.so.6 => /home/comp/chengxu/usr/lib/libc.so.6 (0x00002b491cfdf000)
    /home/comp/chengxu/usr/opt/glibc/lib/ld-linux-x86-64.so.2 (0x00002b491b5c0000)
```

Sorry I cannot solve this on my own as little experience on Linux.

**Comment by xu-cheng** [comment]
Actually I just found the test of readline fails for me.
```
$ brew test readline
Testing readline
==> /home/comp/chengxu/usr/bin/gcc-4.9 test.c -lreadline -o test
/home/comp/chengxu/usr/lib/libreadline.so: undefined reference to `tgetnum'
/home/comp/chengxu/usr/lib/libreadline.so: undefined reference to `PC'
/home/comp/chengxu/usr/lib/libreadline.so: undefined reference to `tgetstr'
/home/comp/chengxu/usr/lib/libreadline.so: undefined reference to `BC'
collect2: error: ld returned 1 exit status
Error: readline: failed
Failed executing: /home/comp/chengxu/usr/bin/gcc-4.9 test.c -lreadline -o test
``

**Comment by iggyvolz** [comment]
It seems to possibly be the same error as http://www.justskins.com/forums/readline-problem-libreadline-so-98137.html, which suggests running ```gcc rl.c -lreadline -ltermcap```.

**Comment by sjackman** [comment]
Iggy's suggestion fixes the linker error:

```diff
diff --git a/Library/Formula/readline.rb b/Library/Formula/readline.rb
index 472f3f6..8f095cd 100644
--- a/Library/Formula/readline.rb
+++ b/Library/Formula/readline.rb
@@ -58,7 +58,7 @@ class Readline < Formula
         return 0;
       }
     EOS
-    system ENV.cc, "test.c", "-lreadline", "-o", "test"
+    system ENV.cc, "test.c", "-lreadline", "-ltermcap", "-o", "test"
     assert_equal "Hello, World!", pipe_output("./test", "Hello, World!\n").strip
   end
 end
```

I get the following odd runtime error after:
```
$ brew test readline -v
Testing readline
==> /usr/bin/gcc test.c -lreadline -ltermcap -o test
==> ./test
Error: readline: failed
<"Hello, World!"> expected but was
<"test> Hello, World!">.

diff:
- Hello, World!
+ test> Hello, World!
? ++++++
```

but I suspect that's a red herring of some odd Mac/Linux difference, and readline is in fact working.

**Comment by sjackman** [comment]
I see the same gdb issue on CentOS 5.10 Linux 2.6.18:

```
$ gdb
Cannot create pipe for readline
```

**Comment by sjackman** [comment]
It's possible that GDB is calling `pipe2` and failing because the kernel doesn't implement that syscall. This issue also affected `xz`. See #348 and #353.

**Comment by sjackman** [comment]
I suspect that this is an upstream bug.

**Comment by sjackman** [comment]
Yep, that's exactly what's happening. See
https://github.com/bminor/binutils-gdb/blob/eb704cb6566cc4594099f49f8a215bab4fa7bbb6/gdb/common/filestuff.c#L385-L386

The same workaround as for `xz` should work for `gdb`, but this issue should be resolved upstream.

**Comment by sjackman** [comment]
@xu-cheng Can you open an issue upstream with gdb? The issue is that glibc implements the `pipe2` syscall, but the Linux kernel does not.

**Comment by sjackman** [comment]
gdb should fall back to `pipe` if `pipe2` is not available at runtime.

**Comment by iggyvolz** [comment]
@sjackman did you commit the test fix yet?  If not I can send in a PR.

**Comment by sjackman** [comment]
No, I have not tested the workaround. Please do. Thanks, Iggy.

**Comment by iggyvolz** [comment]
@sjackman Oddly enough, your workaround does not work for me:

```bash 
$ cat readline.rb|tail -n5
    EOS
    system ENV.cc, "test.c", "-lreadline", "-ltermcap", "-o", "test"
    assert_equal "Hello, World!", pipe_output("./test", "Hello, World!\n").strip
  end
end
$ brew test readline -v
Testing readline
==> /usr/bin/gcc test.c -lreadline -ltermcap -o test
==> ./test
./test: symbol lookup error: /home/ubuntu/workspace/linuxbrew/lib/libreadline.so.6: undefined symbol: UP
Error: readline: failed
<"Hello, World!"> expected but was
<"">.
```

**Comment by sjackman** [comment]
Try `brew install ncurses` and symlink `libtermcap.so` to `libncurses.so`.

**Comment by sjackman** [comment]
See https://github.com/Homebrew/homebrew-dupes/pull/422

**Comment by iggyvolz** [comment]
It still seems to be failing... did I do this right?
```iggyvolz@personal2:~/workspace/linuxbrew/lib (master) $ ln -s libncurses.so libtermcap.so```

(On a side note - did we split into a seperate problem, and if so should this go on another issue?)

**Comment by sjackman** [comment]
Yes, you can open a separate issue for this `brew test readline` issue.
