### ISSUE TITLE
Fix troubleshooting links so that Homebrew doesn't get spammed

### ISSUE THREAD

**Issue by chdiza** [Linuxbrew/legacy-linuxbrew#401]
The links mentioned [here](https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#check-to-see-if-the-issue-has-been-reported) and [here](https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#create-an-issue) point to the Homebrew issue tracker.  They should be changed to point to the Linuxbrew tracker.

This might explain, in part, the rash of Linuxbrew problems that get reported to Homebrew.

**Comment by rwhogg** [comment]
I believe this has been resolved.
