### ISSUE TITLE
python.setup_install_args - puts site-packages in lib64 not lib 

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/legacy-linuxbrew#443]
I'm trying to package a standalone python tool using the standard formula:

```
ENV.prepend_create_path "PYTHONPATH", libexec/"lib/python2.7/site-packages"
system "python", *Language::Python.setup_install_args(libexec)
bin.install Dir[libexec/"bin/*"]
bin.env_script_all_files(libexec/"bin", :PYTHONPATH => ENV["PYTHONPATH"])
```

On Linux, there is a problem:

It creates this (lib):

```
/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib/python2.7
/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib/python2.7/site-packages
```

But everytjing gets installed here (lib64):

```
/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib64
/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib64/python2.7
/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib64/python2.7/site-packages
/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib64/python2.7/site-packages/cutadapt
```

And the wrapper script gets:

```
PYTHONPATH="/bio/linuxbrew/Cellar/cutadapt/1.8.1/libexec/lib/python2.7/site-packages"
```

But because it was put in `lib64` it doesn't work.

Any ideas?

**Comment by tdsmith** [comment]
I'm willing to spend some time troubleshooting this later this week. It would help if someone knows how Python constructs the path to its site-packages and how to detect where packages will be installed. It looks like pure-Python and compiled extensions behave differently?

**Comment by tdsmith** [comment]
What Linux distribution are you using, Torsten?

**Comment by tseemann** [comment]
Red Hat Enterprise Linux Server release 7.1 (Maipo)  - not by choice ;)

I can test on Ubuntu as well if need be.

@gawbul - which Linux distro were you testing on?

**Comment by gawbul** [comment]
@tseemann I was testing on Debian wheezy 7.8 and also Fedora 20. As with https://github.com/Homebrew/homebrew-science/issues/2392 I wonder if adding `ENV.prepend_create_path "PYTHONPATH", libexec/"lib64/python2.7/site-packages"` would work here?

**Comment by sjackman** [comment]
My preference is to hack up the formula to install to `lib` rather than `lib64`.

**Comment by tdsmith** [comment]
Looking at the Python bug tracker, this appears to be a change that certain Linux vendors make to their system Pythons to support mixed 32/64-bit systems. OpenSuSE does this; Ubuntu trusty (afaict?) does not. Apparently RHEL does. Linuxbrew or pyenv pythons should not.

**Comment by tdsmith** [comment]
I think adding `--install-lib=lib` to the string of arguments in `setup_install_args` in `Library/Homebrew/languages/python.rb` may fix this.

**Comment by tdsmith** [comment]
[The distutils docs claim](https://docs.python.org/2/install/#custom-installation) that arguments like `install-lib` are specified relative to `prefix` but that does not appear to be true; this will have to look like `--prefix=~/foo --install-lib=~/foo/lib/python2.7/site-packages`. It's really unfortunate that the python version number is embedded in that string, because setup_install_args isn't supposed to know and can't easily find out which python it's supposed to be calling.

**Comment by tdsmith** [comment]
A ludicrous but effective way to solve this would be to have the `ENV` path methods detect a python site-packages path and also add its lib64 equivalent.

**Comment by tseemann** [comment]
@tdsmith Ludicrous but effective at least makes things work And you could `if OS.linux?` condition it as to not affect OSX users?

**Comment by tdsmith** [comment]
I'd like the fix for this to be using a better Python, built by pyenv or by Homebrew. We could add a doctor check for misbehaving system pythons.

**Comment by sjackman** [comment]
@tseemann Are you using the Homebrew python? If not, try `brew install python`

**Comment by tseemann** [comment]
I can't install Brew python because of this bug: https://github.com/Homebrew/linuxbrew/issues/420
:-(

**Comment by gawbul** [comment]
I was having a read and noticed you can pass a `LIBnn` flag to configure, e.g. `./configure LIBnn=lib`. Would that work in this case?

**Comment by tdsmith** [comment]
No, that's an autotools flag and this is a behavior of some vendors's
modified distutils.
