### ISSUE TITLE
Cyclic dependency involving cmake and curl

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/legacy-linuxbrew#484]
`brew deps` on any of the following packages results in a dependency cycle.

`curl nghttp2 libevent doxygen graphviz pango harfbuzz graphite2 cmake`

**Comment by 1ne** [comment]
Have been struggling with this when using a non-bottled version of curl with the following options. The only workaround I got was to work is to run `brew install curl` before I run this. It feels like a patchwork, not a solution. 
```
~ ❯❯❯ brew install curl --with-c-ares  --with-libmetalink --with-libssh2 --with-nghttp2 --with-rtmpdump
Error: curl contains a recursive dependency on itself:
  curl depends on cmake
  cmake depends on curl
  curl depends on doxygen
  doxygen depends on curl
  curl depends on libevent
  libevent depends on curl
  curl depends on spdylay
  spdylay depends on curl
  curl depends on nghttp2
  nghttp2 depends on curl
```

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#3348

**Comment by rwhogg** [comment]
Thanks for posting the workaround @1ne! I've moved this issue over to linuxbrew/homebrew-core as this repo is now defunct.
