### ISSUE TITLE
glibc: Programs linked against brewed glibc fail to look up username from user id

### ISSUE THREAD

**Issue by waedt** [Linuxbrew/legacy-linuxbrew#500]
Basically what the title says.  For example, running `whoami` from brewed coreutils results in `whoami: cannot find name for user ID 100358403`.

**Comment by sjackman** [comment]
Yes, I can confirm that I've also observed this bug. Do you know whether your system is using LDAP or `/etc/passwd`, or some author authentication system?

**Comment by sjackman** [comment]
If you're using `/etc/passwd`, a workaround may be
```sh
ln -s /etc/passwd `brew --prefix glibc`/etc/
```

**Comment by sjackman** [comment]
I found that the time zone was also incorrect unless I did
```sh
ln -s /etc/localtime `brew --prefix glibc`/etc/
```

**Comment by sjackman** [comment]
You may need to add the `nsswitch.conf` file.
See http://www.linuxfromscratch.org/lfs/view/development/chapter06/glibc.html
and look for `6.9.2.1. Adding nsswitch.conf`.

**Comment by sjackman** [comment]
Perhaps also try
```sh
ln -s /etc/nsswitch.conf `brew --prefix glibc`/etc/
```

**Comment by neil1hart** [comment]
I'm having the same problem after following https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation on red hat.  Our work computer doesn't use /etc/passwd but some other authentication.

whoami
whoami: cannot find name for user ID 11230

/usr/bin/whoami
nhart

**Comment by waedt** [comment]
The workaround I came up with was to symlink `/lib64/libnss_sss.so.2` to `$(brew --cellar)/glibc/2.19/lib/libnss_sss.so.2`.  That fixed the issue for me on Fedora 22.

**Comment by maxim-belkin** [comment]
Thanks for the note. It might be that we have to make `glibc` depend on [sssd](https://fedorahosted.org/sssd/)

**Comment by sjackman** [comment]
On my system where `whoami` fails as above, I noticed that the host glibc has `libnss_ldap.so.2`, but the brewed `glibc` does not have this library.

**Comment by maxim-belkin** [comment]
Fun fact: we need `sssd`, which needs `samba`, which is currently compiled `--without-ldap` ;)

**Comment by sjackman** [comment]
There is the formula `homebrew/dupes/openldap`. Perhaps `samba` could be compiled against that on Linuxbrew.

**Comment by andrewyatz** [comment]
Also just encountered this same problem on RedHat. @waedt solution worked for me though as @maxim-belkin pointed out we're going to need to compile a lot more to make this work.

**Comment by sjackman** [comment]
Glad to hear the workaround worked for you. Would you be interested in submitting a PR for `glibc` that enables compiling `libnss_ldap.so` and `libnss_sss.so`?

**Comment by andrewyatz** [comment]
Ha one PR at a time @sjackman hey ;). 

I'd like to but I'm not sure how much time I have to do this ATMO. I would probably require some help from @maxim-belkin who sounds like they've started down this path and help direct me to a sssd client. All I could find was the sssd distro (https://fedorahosted.org/sssd/) and that seemed to talk more about running daemons vs. clients.

**Comment by sjackman** [comment]
I can't find anything in the [glibc documentation](https://www.gnu.org/software/libc/manual/html_node/Configuring-and-compiling.html) on how to enable `libnss_ldap` or `libnss_sss`. I hope it's in there somewhere. May have to grep through the sources.

**Comment by andrewyatz** [comment]
I think what happens is that if you compile sssd that will generate the
required lib for libnss_sss and deposits that into the /lib64 dir.
Depending on the nss file that tells it what plugins to use when performing
lookups (well that's my guess at least). There's some chatter on the NixOS
GitHub org suggesting this is correct
https://github.com/NixOS/nixpkgs/issues/1868.

**Comment by sjackman** [comment]
Ah, I see. I assumed is was provided by `glibc`.
+ `libnss_ldap.so.2` on [Debian](https://packages.debian.org/jessie/libnss-ldap) is provided by http://www.padl.com/OSS/nss_ldap.html
+ `libnss_sss.so.2` on [Debian](https://packages.debian.org/jessie/libnss-sss) is provided by [sssd](https://fedorahosted.org/sssd/)

**Comment by neil1hart** [comment]
Haven't been back here for a bit.  I followed waedt comment
ln -s /lib64/libnss_sss.so.2 $(brew --cellar)/glibc/2.19/lib/libnss_sss.so.2
resolved my issues with whoami, ls -al, groups

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/brew#145
