### ISSUE TITLE
misleading installation instructions in readme

### ISSUE THREAD

**Issue by niole** [Linuxbrew/legacy-linuxbrew#503]
you should get rid if the **Install Linuxbrew (tl;dr)** section in the Readme. It's misleading

**Comment by sjackman** [comment]
Which other instructions are critical? I think this for sure:
```sh
export PATH="$HOME/.linuxbrew/bin:$PATH"
```

**Comment by niole** [comment]
It's just this header with the first instruction for `ruby`. The entire
process should be shown in one place and one place only so as not to
confuse users regarding the installation process.

**Comment by iggyvolz** [comment]
The entire process is in that one command.  The rest is just installing dependencies and pointing your system to use Linuxbrew stuff by default.

**Comment by niole** [comment]
Don't you agree that that's part of the installation process?

**Comment by sjackman** [comment]
Many systems already have the dependencies installed. The only really critical steps that's missing from the `tl;dr` modifying the `PATH`.

**Comment by niole** [comment]
Oh, gotcha. Excuse me for using issues like stackoverflow
