### ISSUE TITLE
gcc: Removing "--with-system-zlib"

### ISSUE THREAD

**Issue by ccopsey** [Linuxbrew/legacy-linuxbrew#508]
12 Sep 2014, commit 2da651a231654df2c8653fe9b2d14a4238ccaf46 made "--with-system-zlib" a MacOS only option.

10 Oct 2014, commit 95127d482e129197b054cc7c8c5317beb0dc67b2 undoes this change.

Subsequent commits flip-flop back and forth depending upon who made the commit.

As it does not appear to have been reverted intentionally, can this be reinstated (i.e. so that this option is not used in linuxbrew)?

**Comment by sjackman** [comment]
Hi, Chris. Are you seeing a build error that you are trying to fix, and if so, what is the exact error message? Does `brew install zlib` resolve your issue?

**Comment by sjackman** [comment]
Relevant code in `gcc.rb`: https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/gcc.rb#L123-L125

**Comment by ccopsey** [comment]
Hi Shaun,

A system I'm using (and don't have sudo rights for) doesn't have `libz.so` (it does have `libz.so.1`).  I have already successfully built zlib using linuxbrew.

Using `brew install gcc` the build was failing during stage2 because it could not find libz.  By commenting out the option that I mentioned the build succeeded, and because I found confusion in the git logs I assumed that was the problem.

However, whilst building up details of my problem I have discovered that this is actually something else.  By commenting out the above option, gcc was building its own zlib.  Not what I wanted.  What it appears is that LDFLAGS is not passed to stages 2, 3... of the build.  Which is why stage 1 succeeds - it knows about the linuxbrew libraries.

[Line 110 of gcc.rb](https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/gcc.rb#L110) uses the `--with-boot-ldflags` argument to pass LDFLAGS through to stages 2, 3..., but only if `--with-glibc` has been specified as an option to brew.  If I take that line and move it out of the if-clause then my build succeeds.

So, should the `--with-boot-ldflags` be common across all builds to ensure that linuxbrew libraries are used in all stages of the build?

Chris

**Comment by gcstang** [comment]
I'm trying to install this on an Oracle Linux server that is built upon RedHat Linux I keep getting that gcc is needed and that I need to install it like:
brew install gcc
When I do that it tells me I need zlib and zlib tells me it needs gcc... endless circle.
Everything I tried after that needs gcc.
Is there a way around this?
I have gcc installed already on the system, can it use that instead of making me install it using linuxbrew?

Gil

**Comment by sjackman** [comment]
Hi, Gil. Please see #191

**Comment by sjackman** [comment]
> By commenting out the above option, gcc was building its own zlib. Not what I wanted.

GCC usually builds its own `zlib` and eliminates a dependency. Not so bad in my opinion.

**Comment by gcstang** [comment]
Thank you, I found a solution by doing this which I had seen in another thread.

export HOMEBREW_CC=gcc
$ prefix=/usr/local/linuxbrew
ln -s /usr/bin/gcc44 $prefix/bin/gcc-4.4
ln -s /usr/bin/g++44 $prefix/bin/g++-4.4
ln -s /usr/bin/gfortran44 $prefix/bin/gfortran-4.4

It worked after these changes.

Thank you, I love it!

**Comment by sjackman** [comment]
Great. Glad to hear that you got it working, Gil.
