### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by tdsmith** [Linuxbrew/legacy-linuxbrew#528]
What's the story with Linuxbrew and Travis? Noticing that Travis supports Docker now we ought to be able to abuse that to test on Ubuntu and CentOS images.

**Comment by tdsmith** [comment]
-- and the standalone image, which will make bottling easier.

**Comment by tdsmith** [comment]
Docs here: http://docs.travis-ci.com/user/docker/

**Comment by dpo** [comment]
We haven't had too much success so far. One blocking factor is the time it takes to build stuff (especially gcc and the like). We get kicked out.

**Comment by ahundt** [comment]
could the same bottle integration the mac version has speed up some of those steps for things that depend on gcc?

**Comment by saketkc** [comment]
@dpo did manage to hack around that. 
See: https://github.com/Homebrew/homebrew-science/issues/1795#issuecomment-75081443

**Comment by xu-cheng** [comment]
See https://github.com/Homebrew/homebrew-science/pull/2847

**Comment by sjackman** [comment]
I'd happily accept a pull request updating `.travis.yml` on Linuxbrew. I have limited time for troubleshooting, because I'm on parental leave. My son Jake is two months old. In one week I'll be leaving with my family on vacation until Christmas.

**Comment by saketkc** [comment]
Here is a hacked version of `.travis.yml' building: https://travis-ci.org/saketkc/linuxbrew/builds/85045113

It currently complains of `git` missing, which should probably go to @sjackman's Dockerfile?

I am a novice docker user and I am not even sure, if it is going to do properly what it is supposed to.

**Comment by DoomHammer** [comment]
Same here at https://travis-ci.org/DoomHammer/linuxbrew . Not sure about this `git` as it is installed. I guess it might have some library loading problem or maybe something's wrong with repository? Would give it further look later.

Strange thing is, it builds locally under similar Docker pipeline.

**Comment by DoomHammer** [comment]
OK, some success. Now it fails locally, too :)

**Comment by DoomHammer** [comment]
OK. [This one](https://travis-ci.org/DoomHammer/linuxbrew/jobs/85057681) works albeit with a tiny hack. I had to manually `apt-get install git` since _somewhere_ during `test-bot` run my linuxbrew repo is cleared and I have no software brewed whatsoever.

Anybody have any idea how to properly fix this instead of working around?

**Comment by DoomHammer** [comment]
Opened #601 to discuss my approach there.

**Comment by rwhogg** [comment]
I think this issue is probably out of date. Can we close it?
