### ISSUE TITLE
php56 php55 install wants DTrace

### ISSUE THREAD

**Issue by rivimey** [Linuxbrew/legacy-linuxbrew#536]
I believe the reference to DTrace in the php56.rb and php55.rb files are unwanted.

**Comment by iggyvolz** [comment]
I can confirm that DTrace isn't pre-installed on Linux.  It's pre-installed on Macs (which is what the homebrew-php repo was originally intended for), and seems very difficult to build on linux.  I'll open a pull request on the homebrew-php for discussion on how this should be approached.

In the meantime - you can work around this by using --with-phpdbg, as phpdbg conflicts with DTrace so it works on Linux.  There are still tons of other problems with using linuxbrew with homebrew-php.
