### ISSUE TITLE
Python2.7 package coredumps when compiling YouCompleteMe

### ISSUE THREAD

**Issue by BooneJS** [Linuxbrew/legacy-linuxbrew#549]
When compiling YouCompleteMe, line 25 of ~/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py segmentation faults. The line in question is "from tempfile import mkdtemp".

Compiling Python-2.7.10 from source, not the brew package, makes the problem go away.

**Comment by tdsmith** [comment]
Does running that import make a brewed python crash outside of the YouCompleteMe build? Can you provide any more details or a build log (`brew gist-logs python`)?

**Comment by iMichka** [comment]
This issue is pretty old, and is waiting for a response this 2015. Let's close this.

If you still have problems/questions with this, please open a new issue in our new repo: https://github.com/Linuxbrew/homebrew-core
