### ISSUE TITLE
id3lib failed to build on Ubuntu Trusty (14.04.3)

### ISSUE THREAD

**Issue by rwstauner** [Linuxbrew/legacy-linuxbrew#566]
https://gist.github.com/4ef2ae3351c66230c064

I also tried the formula from Homebrew but that didn't help.

I see that id3lib has had several issues in Homebrew, but it currently builds for me on the mac.

**Comment by iMichka** [comment]
This issue is pretty old. I see that we do not have a bottle for id3lib. Nobody is working on this for the moment. If you want this to move forward, please open a new issue in our new repo: https://github.com/Linuxbrew/homebrew-core, and fill out the full issue template. Thanks.
