### ISSUE TITLE
Error: Input/output error @ rb_file_flock

### ISSUE THREAD

**Issue by zeneofa** [Linuxbrew/legacy-linuxbrew#576]
Hi, 

When I try to install any formula, I get the following error:

```
brew install curl
Error: Input/output error @ rb_file_flock - /home/jq2/.cache/Homebrew/Formula/curl.brewing
```

Now I have tried to reinstall brew, did not work
Also tried installing a new version of flock, which also did not work
btw this is not specific to the curl formula, all formulas seem to do this....

Any advice?

**Comment by zeneofa** [comment]
some more information:

brew install -vd curl
/data/home/jq2/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /data/home/jq2/.linuxbrew/Library/Formula/curl.rb
/data/home/jq2/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /data/home/jq2/.linuxbrew/Library/Formula/openssl.rb
/data/home/jq2/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /data/home/jq2/.linuxbrew/Library/Formula/makedepend.rb
/data/home/jq2/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /data/home/jq2/.linuxbrew/Library/Formula/pkg-config.rb
/data/home/jq2/.linuxbrew/Library/brew.rb (Formulary::FormulaLoader): loading /data/home/jq2/.linuxbrew/Library/Formula/zlib.rb
Error: Input/output error @ rb_file_flock - /home/jq2/.cache/Homebrew/Formula/curl.brewing
/data/home/jq2/.linuxbrew/Library/Homebrew/formula_lock.rb:15:in `flock'
/data/home/jq2/.linuxbrew/Library/Homebrew/formula_lock.rb:15:in `lock'
/data/home/jq2/.linuxbrew/Library/Homebrew/formula.rb:691:in `lock'
/data/home/jq2/.linuxbrew/Library/Homebrew/formulary.rb:22:in `to_proc'
/data/home/jq2/.linuxbrew/Library/Homebrew/formula_installer.rb:691:in `each'
/data/home/jq2/.linuxbrew/Library/Homebrew/formula_installer.rb:691:in `lock'
/data/home/jq2/.linuxbrew/Library/Homebrew/formula_installer.rb:99:in `prelude'
/data/home/jq2/.linuxbrew/Library/Homebrew/cmd/install.rb:183:in `install_formula'
/data/home/jq2/.linuxbrew/Library/Homebrew/cmd/install.rb:89:in `install'
/data/home/jq2/.linuxbrew/Library/Homebrew/cmd/install.rb:89:in `each'
/data/home/jq2/.linuxbrew/Library/Homebrew/cmd/install.rb:89:in `install'
/data/home/jq2/.linuxbrew/Library/brew.rb:127:in `send'
/data/home/jq2/.linuxbrew/Library/brew.rb:127

brew doctor:
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The system curl on 10.6 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.
We recommend you:
  brew install curl

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /home/jq2/.linuxbrew/bin/curl-config
    /home/jq2/.linuxbrew/bin/apu-1-config
    /home/jq2/.linuxbrew/bin/ncurses5-config
    /home/jq2/.linuxbrew/bin/ncursesw5-config
    /home/jq2/.linuxbrew/bin/apr-1-config
    /home/jq2/.linuxbrew/bin/pkg-config
    /opt/torque/bin/pbs-config
    /home/jq2/miniconda/bin/xml2-config
    /home/jq2/miniconda/bin/freetype-config
    /home/jq2/miniconda/bin/libpng16-config
    /home/jq2/miniconda/bin/python-config
    /home/jq2/miniconda/bin/libpng-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    blast

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install jpeg libpng pcre

Run `brew missing` for more details.

**Comment by zeneofa** [comment]
I commented out line 15-17 in /data/home/jq2/.linuxbrew/Library/Homebrew/formula_lock.rb, and things seem to work now. Don't know what this will break down the line.

**Comment by sjackman** [comment]
You can try `rm -r /home/jq2/.cache/Homebrew`
If that doesn't do the trick, my best guess would be that your kernel or file system does not support file locking, which would be weird.

**Comment by zeneofa** [comment]
I tried removing the entire directory structure, it did not work. The only thing that appears to work is the commenting of the lines. I have also asked the sys admin for the cluster I am working on if they know what is going on, everybody seems stumped.

**Comment by sjackman** [comment]
What version of Ruby do you have? Please report
```sh
ruby --version
```
and also try
```sh
brew install ruby
```
