### ISSUE TITLE
CMAKE_BUILD_WITH_INSTALL_RPATH breaks the ability to run binaries during Cmake build

### ISSUE THREAD

**Issue by indianajohn** [Linuxbrew/legacy-linuxbrew#583]
Commit 07c4b3896f74cf29894ab67e3c35911866469038 adds both CMAKE_BUILD_WITH_INSTALL_RPATH and CMAKE_INSTALL_RPATH_USE_LINK_PATH to the global cmake flags. For the reasons I listed in my comment on that commit, I believe it makes  sense so remove CMAKE_BUILD_WITH_INSTALL_RPATH from the global CMake flags. I am repeating this issue here for proper tracking/bookkeeping.

My comment below:
On my system, for homebrew-science/vtk, this commit breaks the build. The problem seems to be that VTK builds some binaries and then tries to run them during the build; when it runs the binaries it is unable to load the shared libraries because of the CMAKE_BUILD_WITH_INSTALL_RPATH option. What was the reasoning behind adding the CMAKE_BUILD_WITH_INSTALL_RPATH flag? I understand the need for CMAKE_INSTALL_RPATH_USE_LINK_PATH - the binaries need to be linked properly for running. But at build time, the binaries are not present in the install directory, and therefore any attempt to run them from the build directory will fail.

I removed CMAKE_BUILD_WITH_INSTALL_RPATH from the args list and build vtk again, and the build was successful. If there is no compelling reason to keep CMAKE_BUILD_WITH_INSTALL_RPATH set, would you accept a pull request disabling it again?

**Comment by sjackman** [comment]
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.
