### ISSUE TITLE
Keg.change_rpath and non-native binaries

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/legacy-linuxbrew#606]
I am trying to bottle some formula that I would like to redistribute. Most of the time bottling works OK, but I am having trouble particularly with `libvirt` and `qemu`. They both contain non-native binaries as they are cross-platform by nature. This means that `patchelf` fails miserably and `brew` cannot bottle.

@sjackman: do you think there should be a check in Linuxbrew whether binary is native before switching interpreter and rpath?

**Comment by sjackman** [comment]
Yes, it should check that the executable is native before running `patchelf`.

**Comment by DoomHammer** [comment]
OK, I should try to find a solution, since the current mechanism uses names like `mach_o_binary` which do not belong to Linux(brew) world ;)

**Comment by sjackman** [comment]
True. I don't want to refactor or rename inside Linuxbrew though. The patch should be kept as small as possible to ease the merging maintenance.

**Comment by DoomHammer** [comment]
Seems no longer relevant for new `qemu` formula.

**Comment by sjackman** [comment]
Non-ELF executables (namely Mac executables) no longer have their executable bit set by the Linuxbrew post-installation cleanup code.

**Comment by DoomHammer** [comment]
The original problem was with ELF binaries that were compiled for other platform, I believe (`qemu` has a few of them). But since I cannot reproduce it I consider it fixed.
