### ISSUE TITLE
Error: No such file or directory - (unreachable)/

### ISSUE THREAD

**Issue by prologic** [Linuxbrew/legacy-linuxbrew#608]
This is weird and I can't seem to find an answer to this. I also haven't worked out why this is happening with the `--debug` flag either.

Basically almost anything I _try_ to install ends with:

``` #!bash
Error: No such file or directory - (unreachable)/
```

Example:

``` #!bash
$ brew install python --cc=gcc
==> Installing dependencies for python: pkg-config, homebrew/dupes/ncurses, readline, homebre
==> Installing python dependency: pkg-config
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz
Already downloaded: /home/prologic/.cache/Homebrew/pkg-config-0.28.tar.gz
==> ./configure --prefix=/home/prologic/.linuxbrew/Cellar/pkg-config/0.28 --disable-host-tool --with
==> make
==> make check
==> make install
Error: No such file or directory - (unreachable)/
```

If it would just tell me what file/directory it's complaining about I might be able to fix this :) The `(unreachable)/` part is a bit weird!

**Comment by prologic** [comment]
Running ``brew doctor`` also reports the same issue:

```#!bash
$ brew doctor
Error: No such file or directory - (unreachable)/
```

**Comment by prologic** [comment]
If it helps my ``$HOME`` is mounted over NFS.

**Comment by sjackman** [comment]
That is a very strange error message. I suspect that the NFS file system is relevant. I also run Linuxbrew on a NFS file system though, and haven't run into this error message. Does `brew install hello` work?

**Comment by prologic** [comment]
No it doesn't; it fails with the same error at the end.

**Comment by sjackman** [comment]
You definitely have bigger problems, though I'm not sure what exactly. Sorry. :grimacing: I leave for a two-month trip tonight, so I won't be able to help you troubleshoot.

**Comment by prologic** [comment]
Yeah that's okay; I'm not sure what to do at this point :) I'm sort-of trying to do this whilst doing other more important thing :) -- Enjoy your trip! I'll see what I can work out in the mean time...

**Comment by sjackman** [comment]
Try it in a non-NFS partition to eliminate that possible source of trouble.

**Comment by rwhogg** [comment]
Closing this as it is unreproducible.
