### ISSUE TITLE
gcc circular dependency Fedora 22

### ISSUE THREAD

**Issue by gregory-nisbet** [Linuxbrew/legacy-linuxbrew#609]
I am using Fedora 22, `brew doctor` gave the following message, but it seems rather harmless

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /bin/pkg-config
    /bin/x86_64-redhat-linux-gnu-pkg-config
    /bin/icu-config
    /bin/brltty-config
```

When I try to install `gcc`, I get a weird circular dependency (initially I was trying to install `opam`). Also, I already have gcc 5.1.1 installed via `dnf`.

```
$ brew install gcc
==> Installing dependencies for gcc: zlib, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

This Dockerfile reproduces the problem.

```
FROM fedora:22
RUN dnf -y update
RUN dnf -y groupinstall 'Development Tools'
RUN dnf -y install ruby-2.2.3 which tar

RUN useradd a
WORKDIR /home/a
USER a
RUN ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
RUN echo 'export PATH="/home/a/.linuxbrew/bin:$PATH"' >> /home/a/.bashrc
RUN source /home/a/.bashrc
```

**Comment by DoomHammer** [comment]
Try `brew install opam --cc=gcc`

**Comment by sahilseth** [comment]
Facing the same issue:

```
brew install opam --cc=gcc
Warning: opam-1.2.2_1 already installed
```


```
brew install zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

**Comment by gregory-nisbet** [comment]
@DoomHammer `brew install opam --cc=gcc` worked for me right out of the box.

I am a bit surprised `aspcud` isn't listed as an explicit dependency of `opam`, since that's the preferred dependency solver for the project. Oh I see, the logic in `opam.rb` doesn't take Linux into account.

    # aspcud has a fairly large buildtime dep tree, and uses gringo,
    # which requires C++11 and is inconvenient to install pre-10.8
    if MacOS.version > 10.7
      depends_on "aspcud" => :recommended
    else
      depends_on "aspcud" => :optional
    end

Building aspcud from source should work pretty well on just about every Linux though.

The `aspcud` recipe itself is kind of a minefield though. First it chokes on a missing dependency `makedepend`, and then later it complains about a missing `/home/<user>/.linuxbrew/opt/pkg-config`. I never created such a file and don't know what it is supposed to do. I'll look into fixing the recipe.

@sahilseth What version of gcc and what distribution are you using?

**Comment by ylluminate** [comment]
Having the same issue here.  I hadn't updated `linuxbrew` for quite some time on this server, and then upon update && upgrade, I found that I was hitting walls with a supposed missing `gcc`.  

```
brew install gcc
==> Installing dependencies for gcc: zlib, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: zlib
Error: zlib cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

Running CentOS / CloudLinux 6.7 here.

**Comment by ylluminate** [comment]
So, it appears that `brew install gcc --cc=gcc` resolved the issue, althought I had to step backwards first through some dependencies that were being complained about... and so ultimately providing `--cc=gcc` each time I hit a wall on a dep got me past that.

**Comment by sjackman** [comment]
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.

**Comment by suhlig** [comment]
I had the same issue on RHEL 6.7, and [symlinking the existing gcc helped](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc).
