### ISSUE TITLE
issues with Crti.o when installing gcc

### ISSUE THREAD

**Issue by DimitriDokuchaev** [Linuxbrew/legacy-linuxbrew#634]
Hello

I am fallowing [this tutorial](https://github.com/Homebrew/linuxbrew/wiki/Chromebook-Install-Instructions) to install linuxbrew on my chromebook.

But i am having an issue where i can't install gcc.

I did `brew install gcc --with-glibc -v` (as written in the tutorial)

it dies here:

`/usr/local/linuxbrew/Cellar/binutils/2.25.1/x86_64-unknown-linux-gnu/bin/ld: cannot find crti.o: No` such `file or directory`
`/usr/local/linuxbrew/Cellar/binutils/2.25.1/x86_64-unknown-linux-gnu/bin/ld: cannot find` `/usr/lib64/libc_nonshared.a`
`collect2: error: ld returned 1 exit status`
`make[3]: *** [libgcc_s.so] Error 1`
`make[3]: Leaving directory`/usr/local/linuxbrew/tmp/gcc20151107-18897-p6hyft/gcc`-`5.2.0/build/x86_64-unknown-linux-gnu/libgcc'`
`make[2]: **\* [all-stage1-target-libgcc] Error 2`
`make[2]: Leaving directory `/usr/local/linuxbrew/tmp/gcc20151107-18897-p6hyft/gcc-5.2.0/build'`
`make[1]: *** [stage1-bubble] Error 2`
`make[1]: Leaving directory`/usr/local/linuxbrew/tmp/gcc20151107-18897-p6hyft/gcc-5.2.0/build'`
`make: **\* [bootstrap] Error 2`

To troubleshoot i checked if crti.o existed with 

`find -name crti.o`

which returned 

`./usr/local/linuxbrew/lib/crti.o`
`./usr/local/linuxbrew/Cellar/glibc/2.19/lib/crti.o`
`./usr/local/lib/crti.o`

Therefor it exists and it is present, I don't know why it's not working.

I can provide the whole log if needed, also sorry for the Markdown issues as i am still figuring it out.

**Comment by ahundt** [comment]
I encountered some issues like this, perhaps they can help you solve your problems:
https://github.com/Homebrew/linuxbrew/issues/530
https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation

**Comment by DimitriDokuchaev** [comment]
Hey ahundt 

Following your issue i see you do have a problem with gawk, i have it installed and it is working correctly

further you posted a script that can't really be applied to my system, since this is a chromebook, so no apt-get install build-essential all that stuff.

I am actually going through your script and the original chromebook tutorial, trying to realize what separates them and if there is anything in common, i am pretty new to linuxbrew so I am still trying to get around all this, I ll try to update this post, if I go any further.

Thanks ahundt

**Comment by ahundt** [comment]
Yeah I realize it won't apply perfectly but hopefully there will be a hint or solution that you can translate to your platform. I have several links specifically about fixing crti.o problems further down in the discussion.

https://github.com/Homebrew/linuxbrew/issues/530#issuecomment-144211035
https://stackoverflow.com/questions/32855096/building-linuxbrew-homebrew-standalone-version-on-ubuntu-14-04

**Comment by sjackman** [comment]
The path to `crti.o` can be specified using either the `gcc` option `-B` or the environment variable `LIBRARY_PATH`, otherwise it uses the host `crti.0`, which seems to usually work.
