### ISSUE TITLE
Key dependencies should have "linuxbrew" and "system" config option

### ISSUE THREAD

**Issue by ahundt** [Linuxbrew/legacy-linuxbrew#640]
Key dependencies like gcc, libstdc++, X11 currently behave in an inadvertently disorderly manner leading to crashes and other undesired behavior. A mechanism should be created where you choose how you want specific key dependencies to actually work, or if possible a transparent solution should be devised like however it works on OS X. 
## How to accidentally break a normal install

For example, if I do the following I will end up with a broken configuration:

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
PATH="~/.linuxbrew:$PATH"
export PATH
brew tap homebrew/science
brew install boost
brew install gcc
brew install pcl
```

Now boost will be compiled with the system gcc and pcl will be compiled with the linuxbrew version. Then, as soon as you try to run any code that uses these dependencies it will crash due to version conflicts, particularly if both use libstdc++.

One particularly silent way for this to happen is if you install some tools, then install a tool that depends on gcc and libstdc++. The version in use will simply change between different tools that have been installed!

Things get particularly hairy if you use any dependencies in homebrew-science that use fortran.
## How to accidentally break a [standalone install](https://github.com/Homebrew/linuxbrew/wiki/Standalone-Installation)

Additionally, if you use the standalone version, there doesn't appear to be any clear way to use a linuxbrew compiled X11, or even the system version. This issue appears to be manifesting itself in #632. 
## naive solution

the naive solution is to stick linuxbrew at the end of the path, however this will lead to unwanted behavior. For example try:

```
PATH="$PATH:~/.linuxbrew"
brew install cmake
cmake --version
```

If cmake is already on your system you will get the system version, which isn't what is desired!
## Initial solution idea

Add a "system-coredep" and "linuxbrew-coredep" flag to the linuxbrew setup with a reasonable default.

My first idea for how to solve this problem is to allow a flag at linuxbrew installation time.

**system-coredep**
- use certain system dependencies and mark them as "installed" in the dependency list, particularly gcc, libstdc++, and X11

**linuxbrew-coredep**
- every possible core dependency will be built (or perhaps bootstrapped) by linuxbrew
  lets you specify a list of system dependencies you
- not sure how this will deal with X11 in particular
## Other ideas?

Has anyone had to deal with problems like this before? Anyone have other possible ideas?

**Comment by sjackman** [comment]
Good questions, Andrew.
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.
