### ISSUE TITLE
Cannot build fontconfig on linux [nsgmls:(invalid location)]

### ISSUE THREAD

**Issue by mu22le** [Linuxbrew/legacy-linuxbrew#655]
So, fontconfig fails at build, the relevant error seems to be:
Working on: /tmp/fontconfig20151118-14198-2crw76/fontconfig-2.11.1/doc/local-fontconfig-devel.sgml
nsgmls:(invalid location):E: invalid filename ""

Possible things that I have done wrong: 
- brew doctor complains about a few headers in /usr/local/include, but I don't have write permission there, so there is nothing to do about them.

Here is the relevant gist:
https://gist.github.com/03f50a88348d4668d3da

**Comment by aklatzke** [comment]
This appears to be related to docbook-utils and not LinuxBrew.

On a CentOS environment I ran: 

`yum remove docbook-utils`

And was able to successfully install something with fontconfig as a dependency.

**Comment by mu22le** [comment]
Thanks a lot for the help. Unfortunately the reason I'm using homebrew is that I do not have root access on this machine, I cannot remove docbook-utils. Would it even be possible to install a homebrewed version of nsgmls and have fontconfig use that?

**Comment by sjackman** [comment]
I'm afraid that I don't have the time available to help troubleshoot individual formula. If you're able to find a work around or solution, please post it here. Sorry that I couldn't be of more help.

**Comment by mu22le** [comment]
@aklatzke, thanks anyway!
@sjackman could you tell me what recipe homebrew installed to provide nsgmls whaen you removed docbook-utils?

**Comment by koheimiya** [comment]
I managed the same problem without root access.
Just `brew install fontconfig --without-docs`.
May be too late, but I hope it helps someone in a similar situation.
