### ISSUE TITLE
Multiple errors when trying to install pkg-config

### ISSUE THREAD

**Issue by mistydemeo** [Linuxbrew/legacy-linuxbrew#667]
_From @CoolOmar2020 on November 25, 2015 19:56_

hi , I am trying to install OpenGL libraries & i don't have root account but I always fail due to 

dependency pkg-config failing to install

here's the log:

Already downloaded: /mnt/user/.cache/Homebrew/pkg-config-0.28.tar.gz  
==> ./configure --prefix=/mnt/user/.linuxbrew/Cellar/pkg-config/0.28 --disable-host-tool --with-internal-glib --with-pc-path=/mnt/user/.linuxbrew/lib/pkgconfig:/
==> make  
Error: Suspicious failure  
Cool_Omar@OpenGL:/mnt/project$ brew doctor  
Your system is ready to brew.  
Cool_Omar@OpenGL:/mnt/project$ brew install pkg-config  
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz  
Already downloaded: /mnt/user/.cache/Homebrew/pkg-config-0.28.tar.gz  
==> ./configure --prefix=/mnt/user/.linuxbrew/Cellar/pkg-config/0.28 --disable-host-tool --with-internal-glib --with-pc-path=/mnt/user/.linuxbrew/lib/pkgconfig:/
==> make  
Last 15 lines from /mnt/user/.cache/Homebrew/Logs/pkg-config/02.make:  
See file:///usr/share/doc/gcc-4.8/README.Bugs for instructions.  
make[6]: **\* [gchecksum.lo] Error 1  
make[6]: **\* Waiting for unfinished jobs....  
make[6]: Leaving directory `/tmp/pkg-config20151125-21444-1ddx02m/pkg-config-0.28/glib/glib'                                                                     
make[5]: *** [all-recursive] Error 1                                                                                                                             
make[5]: Leaving directory`/tmp/pkg-config20151125-21444-1ddx02m/pkg-config-0.28/glib/glib'  
make[4]: **\* [all] Error 2  
make[4]: Leaving directory `/tmp/pkg-config20151125-21444-1ddx02m/pkg-config-0.28/glib/glib'                                                                     
make[3]: *** [all-recursive] Error 1                                                                                                                             
make[3]: Leaving directory`/tmp/pkg-config20151125-21444-1ddx02m/pkg-config-0.28/glib'  
make[2]: **\* [all] Error 2  
make[2]: Leaving directory `/tmp/pkg-config20151125-21444-1ddx02m/pkg-config-0.28/glib'                                                                          
make[1]: *** [all-recursive] Error 1                                                                                                                             
make[1]: Leaving directory`/tmp/pkg-config20151125-21444-1ddx02m/pkg-config-0.28'  
make: **\* [all] Error 2                                                                                                                                          

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting                                               

These open issues may also help:  
pkg-config files point to versioned source https://github.com/Homebrew/homebrew/issues/44272  
document pkg-config configuration  https://github.com/Homebrew/homebrew/issues/21129  
ossp-uuid patch pkg-config to use configured dirs https://github.com/Homebrew/homebrew/pull/43889  

_Copied from original issue: Homebrew/homebrew#46365_

**Comment by sjackman** [comment]
I'm traveling until the new year. If you haven't yet found a workaround or solution for this issue, please bump this thread after then. Sorry for the delay.

**Comment by iggyvolz** [comment]
Could you run brew gist-logs pkg-config and post the link here?  There's lots of under-the-hood information that isn't reported by the front-end that is very useful.

**Comment by CoolOmar2020** [comment]
https://gist.github.com/anonymous/33b14151949115ff58ae

**Comment by iggyvolz** [comment]
From looking at some bug reports similar, it looks like you ran out of memory on your system.  Some possible workarounds involve modifying CFLAGS manually, which will get really messy with Linuxbrew.  Are you working on a low-memory system, and if so, is there any way you could install more memory?

**Comment by tseemann** [comment]
@iggyvolz Maybe not a physical RAM issue but running on a cluster with RAM quota or similar?
