### ISSUE TITLE
pkg-config cannot find system libraries

### ISSUE THREAD

**Issue by sryze** [Linuxbrew/legacy-linuxbrew#669]
It seems that linuxbrew's `pkg-config` cannot find system libraries like gtk+-3.0 or libfreetype installed via apt-get on Ubuntu 15.10.

I was trying to build [tilda](https://github.com/lanoxx/tilda) the other day and its configure script kept complaining about missing gtk+-3.0 package, I couldn't figure out why because it was certainly present on the system. Then I noticed that it was using the linuxbrew version of pkg-config so I removed `~/.linuxbrew/bin/pkg-config` from `PATH` and GTK was happily found (i.e. now via the system's `pkg-config`).

I also tried adding the location of `gtk+-3.0.pc` to the `PKG_CONFIG_PATH` variable prior to that but it didn't help.

linuxbrew version: 0.9.5 (git revision 092bb; last commit 2015-11-17)

**Comment by sjackman** [comment]
Linuxbrew aims to use its own libraries as much possible. Try `brew install gtk`. I'm on vacation until the new year. If this issue is still a problem for you after then, please bump this thread. Sorry for the delay.
