### ISSUE TITLE
profanity formula depends on libuuid

### ISSUE THREAD

**Issue by benjaminfjones** [Linuxbrew/legacy-linuxbrew#674]
Trying to `brew install profanity` in a fresh linuxbrew environment, first I get a failure on 'libgcrypt'. After working around the issue (see #470) the profanity build system fails because it cannot find 'libuuid'. There is a formula for libuuid, but it conflicts with 'ossp-uuid' which is installed by one of the dependencies.

Full build log:

https://gist.github.com/b47a37d7325eef2e8ed1

**Comment by sjackman** [comment]
I'm on vacation until the new year. If this issue is still a problem for you after then, please bump this thread. Sorry for the delay.
