### ISSUE TITLE
Upgrade of libspatialite Fails

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/legacy-linuxbrew#718]
The gist logs are here...https://gist.github.com/anonymous/aa923f4067ca605ad868

The test log... 
[test-suite.log.txt](https://github.com/Homebrew/linuxbrew/files/90638/test-suite.log.txt)

**Comment by sjackman** [comment]
`make check` has failed for some reason. I'll see if I can reproduce it.
See https://gist.github.com/anonymous/aa923f4067ca605ad868#file-02-make-L1454
