### ISSUE TITLE
gcc: Glibc warning regarding _FORTIFY_SOURCE breaks gcc compilation

### ISSUE THREAD

**Issue by curufinwe** [Linuxbrew/legacy-linuxbrew#803]
The current glibc (2.19) has the following warning:

> _FORTIFY_SOURCE requires compiling with optimization (-O)

in features.h:341

When `./configure` is run for gcc it performs feature-checks with `_FORTIFY_SOURCE=2` and no optimization flag. This warning causes the feature-checks to fail. Thus some headers are believed to be missing and compilation of gcc fails as stuff like `free` and `LONG_MIN` are undefined.
I fixed gcc compilation by commenting out the warning. Thus I cannot upload a gist atm. I will see if I can reproduce the error later at home in a VM.

OS: Ubuntu 12.04
Linuxbrew version: 1d35a3484c16639be18e95d30ad194f13a5639ca

**Comment by sjackman** [comment]
How strange. Can you find an upstream bug report for this issue, and if not, can you please report it upstream?

**Comment by curufinwe** [comment]
It seems I am [not the only one](https://lists.archlinux.org/pipermail/arch-dev-public/2013-April/024776.html) who ran into this. But there the fix was to adjust the build flags. As glibc also caused compile failures for other programs I have removed it and moved to an older version of linuxbrew where glibc is not a hard dependency.

**Comment by sjackman** [comment]
I'm experimenting with rolling out bottles (precompiled binaries) on Linuxbrew, and that requires updating `glibc` on older systems with `glibc` < 2.19. See #380. You're my guinea pig. Congratulations? If you wish to opt out of being my guinea pig, use `brew install -s git` or `export HOMEBREW_BUILD_FROM_SOURCE=1`.

**Comment by sjackman** [comment]
My machine reports `checking for _FORTIFY_SOURCE predefine... no`, so it seems this issue likely only affects compilers that predefine `_FORTIFY_SOURCE`. Please report `brew gist-logs glibc`.
