### ISSUE TITLE
rstudio-server: Depends on pam

### ISSUE THREAD

**Issue by dfornika** [Linuxbrew/legacy-linuxbrew#819]
https://gist.github.com/dfornika/b2d2121c3a356d4370bc

**Comment by sjackman** [comment]
https://gist.github.com/dfornika/b2d2121c3a356d4370bc#file-03-make-L159
```
[ 41%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/system/file_monitor/LinuxFileMonitor.cpp.o
In file included from /tmp/rstudio-server20160216-17306-19anuqx/rstudio-0.99.878/src/cpp/core/system/Pam.cpp:16:0:
/tmp/rstudio-server20160216-17306-19anuqx/rstudio-0.99.878/src/cpp/core/include/core/system/Pam.hpp:16:31: fatal error: security/pam_appl.h: No such file or directory
compilation terminated.
```
It looks as though `rstudio-server` requires `pam` for authentication, and Linuxbrew does not package `pam`. You could check the `configure` options for `rstudio-server` and see if the `pam` dependency can be disabled. You could symlink the pam headers and libraries from your host system into the Linuxbrew prefix. I like making a dummy package when doing this.
```sh
mkdir -p `brew --prefix`/pam/1.2.3/{include,lib}`
ln -s /usr/include/security `brew --prefix`/pam/1.2.3/include
brew link pam
```

**Comment by sjackman** [comment]
You could also create a formula for `pam` and submit it to Linuxbrew. http://www.linux-pam.org/

**Comment by dfornika** [comment]
Thanks for the suggestions. I've tried setting up a dummy package. I had to adjust your bash snippet a bit (put `pam` in the `Cellar` directory):

```
mkdir -p `brew --prefix`/Cellar/pam/1.2.3/{include,lib}
ln -s /usr/include/security `brew --prefix`/Cellar/pam/1.2.3/include
brew link pam
```
It got the build a bit further, but it looks like it's still having trouble finding the `pam` library, and also not finding `boost` if I'm reading the compile log correctly. Here is an updated gist:

https://gist.github.com/204d1c767f50ad083df1

It looks like the rstudio-server formula is in [relatively active development](https://github.com/Homebrew/homebrew-science/commits/master/rstudio-server.rb) so I might get in touch with the maintainers to ask for suggestions or request that they package `pam`

**Comment by sjackman** [comment]
> I had to adjust your bash snippet a bit (put pam in the Cellar directory)

Right. My mistake.

> It got the build a bit further, but it looks like it's still having trouble finding the pam library

Yes, you'll have to create the symlinks for the `pam` libraries as well. `brew unlink pam; make the lib symlinks; brew link pam`

https://gist.github.com/dfornika/204d1c767f50ad083df1#file-03-make-L211
```
/data/home/dfornika/.linuxbrew/bin/ld: cannot find -lpam
/data/home/dfornika/.linuxbrew/bin/ld: cannot find -lboost_date_time
```

Hmm. That should work. `rstudio-server` depends on `homebrew/versions/boost150` and sets the `cmake` variable `BOOST_ROOT`, which I presume should tell it where to find the libraries.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#1849
