### ISSUE TITLE
QT3 Building Failure

### ISSUE THREAD

**Issue by ylluminate** [Linuxbrew/legacy-linuxbrew#843]
I'm needing to install QT3 on an Ubuntu 15.04 system for running `Unstoppable Copier` for a particular situation that I'm facing.  Unfortunately this utility requires `libqt3-mt` and so I thought it would behoove me to cut straight to the chase by building it directly from `http://qt.mirror.constant.com/archive/qt/3/qt-x11-free-3.3.8b.tar.gz`.

It seems to configure just fine, but then when I actually `make` the source, I hit an error:
https://gist.github.com/54cf2d92d91d56c6bf18

Regrettably this isn't clear to me as to what is failing on this build.  Any ideas as to what is going on here and what additional libs may be needed in Homebrew to make this work?

**Comment by sjackman** [comment]
I'm afraid I don't really have the time to help troubleshoot this issue. Sorry.

https://gist.github.com/ylluminate/54cf2d92d91d56c6bf18#file-gistify622562-txt-L164
```
../include/qvaluelist.h:91:13: error: ‘ptrdiff_t’ does not name a type
```

Please post `brew install qt; brew gist-logs qt`. Perhaps someone else may be able to help you.

**Comment by sjackman** [comment]
Do you have root access? If so, installing QT with `apt-get` may be easier. X11 support for Linuxbrew is not well tested nor supported.

**Comment by rwhogg** [comment]
X11 support on Linuxbrew is now available.
