### ISSUE TITLE
scons ignores PATH environment variable (mongodb does not build on CentOS 6.7)

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/legacy-linuxbrew#845]
I am trying to setup Linuxbrew environment on CentOS 6.7

Several formulas (subversions's serf, mongodb) are using scons for the build and it seems that 
it uses own definition of PATH to find various tools as a feature.
http://scons.org/doc/1.1.0/HTML/scons-user/x1673.html

This results in very funny errors:
- Output: https://gist.github.com/eiennohito/4406be3e901cd6084c4c
- config.log: https://gist.github.com/anonymous/6940d56dbf847997c5bc#file-config-log-L425

It seems that because of `PATH` issues, system `ld` was used instead of brewed gcc one.

Patching `SConstruct` file seem hacky, more common solution would be better I believe.
If you have any ideas, please share them.

Default scons `PATH` is hardcoded:
https://github.com/azatoth/scons/blob/master/src/engine/SCons/Platform/posix.py#L233
Maybe we should patch it?

**Comment by eiennohito** [comment]
Quick and dirty patch for scons:
https://github.com/ku-nlp/linuxbrew/commit/f3fbb3a2a28079da4941f596cdca3d795661850a

With it, I was able to install mongodb (semi-manually, #841 still is present and gcc 5.3 gives some warnings that have failed build because of https://jira.mongodb.org/browse/SERVER-13724).

**Comment by sjackman** [comment]
Perhaps this solution: http://scons.org/doc/1.1.0/HTML/scons-user/x1673.html
```python
        import os
        env = Environment(ENV = os.environ)
```

**Comment by sjackman** [comment]
I can confirm that I also see this error:
https://gist.github.com/eiennohito/4406be3e901cd6084c4c#L40
```
Compiler must support a thread local storage class for trivially constructible types
```
In the future, please use `brew gist-logs mongodb`

**Comment by eiennohito** [comment]
Yes, that solution will probably work, but you would have to patch every formula that uses scons.
Another option is to patch scons as I have done and I do not really know what is better.

>In the future, please use brew gist-logs mongodb

It did not upload scons log when I tried.

**Comment by sjackman** [comment]
> It did not upload scons log when I tried.

I see. Thanks. I guess `brew gist-logs` needs to be fixed to include the log output of `scons`.

**Comment by sjackman** [comment]
Then how about changing
```python
env['ENV']['PATH']    = '/usr/local/bin:/opt/bin:/bin:/usr/bin'
```
to
```
env['ENV']['PATH']    = os.environ['PATH']
```

**Comment by eiennohito** [comment]
That should probably work the best as homebrew sets the `PATH` to have everything its need.
I will submit a pull request when I get to university.

**Comment by sjackman** [comment]
Great. Thanks, Arseny. I may not be able to merge it until Monday.

**Comment by eiennohito** [comment]
I though a bit more about it, and how about a patch for scons that adds "homebrew" platform. And selects it when a homebrew variable is set.
https://gist.github.com/eiennohito/bb38a042e8fe4cadfd08

It to patch as the initial suggestion, the scons behavior will be completely different from a pristine one.
What do you think?

**Comment by sjackman** [comment]
Hmm. I think I prefer your original suggestion of simply adding `$HOMEBREW_PREFIX/bin` to the default `PATH` of SCons. I'm okay with that solution. It's simpler.

**Comment by iMichka** [comment]
I see that some changes made it into the repo. We do have a scone bottle now, and it seems to work fine, at least in our docker image.

Let's close this. If you still have problems/questions, please open a new issue in our new repo: https://github.com/Linuxbrew/homebrew-core
