### ISSUE TITLE
Linking lib64 to brew prefix

### ISSUE THREAD

**Issue by yesimon** [Linuxbrew/legacy-linuxbrew#855]
Right now lib64 files are not linked to `brew --prefix`, but some formulas install libraries there, like libffi and liblapack. I'm guessing this is because lib64 is unused in OS X, but in linuxbrew, I think it would make sense to link lib64 files. Otherwise each formula needs an extra workaround section to copy `lib64/*` to `lib/`.

**Comment by maxim-belkin** [comment]
yesimon, google up Linuxbrew Standalone installation. creating a `lib64` symlink to `lib` is one of the steps there. Good luck.

**Comment by yesimon** [comment]
I know about the `lib64` symlink to `lib`. The problem is that formulas might install things to `brew --prefix/opt/myprogram/lib64/liblibrary.so`, which does not get symlinked to `$(brew --prefix)/lib/liblibrary.so` OR `$(brew --prefix)/lib64/liblibrary.so`. Therefore my standalone GCC won't link to it because it sets the rpath as `$(brew --prefix)/lib`

Also, creating a lib64 symlink manually is only in the Ubuntu instructions and I'm not using Ubuntu. The symlink from `lib64` to `lib` is actually created in the glibc formula.

**Comment by yesimon** [comment]
Please see: Homebrew/homebrew-dupes#573

**Comment by sjackman** [comment]
I think that this issue should be fixed in the `cleaner.rb` method `Cleaner::clean`, so it fixes all formulas with this issue. Would you like to take a stab at a fix and a pull request?
