### ISSUE TITLE
tmux: Segfault on linux standalone RHEL6.7

### ISSUE THREAD

**Issue by yesimon** [Linuxbrew/legacy-linuxbrew#867]
tmux version: 2.1

I'll follow up with more detailed debugging information later, but the general gist is that it compiles and installs, but segfaults when starting the program. Debugging under gdb revealed that it is segfaulting on https://github.com/tmux/tmux/blob/2.1/tmux.c#L210, which is `int flags = 0;`. This is pretty mysterious.

To debug this, I tried compiling from source under different conditions than a "pure" linuxbrew `PATH`. First I tried `CC=/usr/bin/gcc ./configure...`, which resulted in the same behavior. Then I tried `PATH=/usr/bin:/bin:$PATH ./configure...`, which actually produced a binary that didn't segfault on program start.

**Comment by sjackman** [comment]
Hi, Simon. Sorry for the difficulty that you experienced. `tmux` has a binary bottle now. Would you like to give that a shot?
