### ISSUE TITLE
openssl upgrade fails if Linuxbrew cURL installed

### ISSUE THREAD

**Issue by erigler-usgs** [Linuxbrew/legacy-linuxbrew#883]
An update to the openssl formula was recently released, and while I don't use it directly much, several packages I use were trying to force me to update it as a dependency. Turns out, when you `brew upgrade openssl`, Linuxbrew removes the openssl prior to downloading the updated version. In doing so, it breaks the Linuxbrewed cURL, which requires openssl to download from a https website. The error message is not exactly clear, and seems to actually indicate that the file could not be found on the server, which was definitely not the case. Fortunately, Linuxbrew cleanly recovers, and re-installs the original version of openssl before exiting the upgrade with a failure message.

My solution was simply to remove Linuxbrew's cURL, upgrade openssl (which uses the system-installed cURL), then re-install Linuxbrew's cURL. I think the ideal solution would be to slightly alter Linuxbrew's sequence of operations so that updated packages were always downloaded before the old package was removed, but I imagine this is something fairly central to Homebrew that Linuxbrew shouldn't change on its own. I suppose another approach is to run `brew fetch`, then `brew upgrade` as two separate commands.

To be clear, it is never recommended in the Linuxbrew installation instructions that a Linuxbrewed cURL be installed, and I can't recall if I installed it deliberately, or if it was installed as a dependency for something else. I'm guessing the former, since it seems to me that this bug would have cropped up previously.

**Comment by sjackman** [comment]
I'd like to fix this bug. I'll have to think on how to fix it properly. The workaround is
```sh
brew fetch openssl curl
brew upgrade
```

> I can't recall if I installed it deliberately, or if it was installed as a dependency for something else

It was likely installed as a dependency. You can check with
```sh
brew uses --installed curl
```

**Comment by DoomHammer** [comment]
Same happens with `zlib` and probably all other `curl` deps.

**Comment by retokromer** [comment]
@sjackman You may add before your patch:
`brew uninstall curl`

**Comment by sjackman** [comment]
Done.

**Comment by DoomHammer** [comment]
Does "Done" mean that we will no longer experience similar issues? I got lost a bit.

**Comment by retokromer** [comment]
It's the workaround.

**Comment by DoomHammer** [comment]
Ah, thanks :)

**Comment by sjackman** [comment]
Sorry for the confusion. This issue persists. Another workaround that may work is…
```sh
LD_LIBRARY_PATH=`brew --prefix openssl`/lib brew upgrade openssl
```
