### ISSUE TITLE
intltool requires XML::Parser

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/legacy-linuxbrew#931]
`intltool` requires Perl's `XML::Parser` library which is probably available on OS X systems, but not so on most Linux hosts. What would be the best way to approach this problem in a systematic manner?

**Comment by sjackman** [comment]
You can add
```ruby
depends_on "XML::Parser" => :perl unless OS.mac?
```
Unfortunately that means `intltool` and anything that depends on it won't be tested by Travis CI.

You can add a `brew doctor` test that check that `XML::Parser` is installed if Perl is installed.

**Comment by sjackman** [comment]
We have a similar problem with Python libraries as well that are installed by default on Mac OS, like `setuptools`.

**Comment by DoomHammer** [comment]
@sjackman why adding this dependency will prevent tests from execution? This would be an undesirable situation.

Checks for XML::Parser and other "standard" libs seem fine for me. Do we have a list of such libs?

**Comment by sjackman** [comment]
I forget the exact situation. We'll have to check. If the language dependency `depends_on "XML::Parser" => :perl` is not installed, it definitely won't be tested. If it is already installed, the testing may work just fine.
