### ISSUE TITLE
test-bot: No output has been received in the last 10m0s on Travis

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/legacy-linuxbrew#939]
```
==> brew uses --recursive python3
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

https://travis-ci.org/Linuxbrew/linuxbrew/builds/116180274#L654-L659

**Comment by sjackman** [comment]
@xu-cheng I see that you added `HOMEBREW_VERBOSE_USING_DOTS` for Travis. Could you possibly also add `HOMEBREW_VERBOSE_USING_DOTS` support to `brew uses`?

**Comment by sjackman** [comment]
`brew uses --recursive python` takes 22 min on my system.
```
❯❯❯ time brew uses --recursive python |wc
   1190    1190   13437

real	22m10.669s
user	20m10.225s
sys	1m6.871s
```

**Comment by xu-cheng** [comment]
> I see that you added HOMEBREW_VERBOSE_USING_DOTS for Travis. Could you possibly also add HOMEBREW_VERBOSE_USING_DOTS support to brew uses?

No, I can't.

> brew uses --recursive python takes 22 min on my system. Is this expected?

We are now seeing this on Homebrew as well. A short time fix may be developed. But that's to be said, there are more deep issues here which require long time solution.

**Comment by sjackman** [comment]
For now I've simply disabled `--recursive` in `brew test-bot` on Linuxbrew.

**Comment by rwhogg** [comment]
We're now seeing this a lot on Circle CI (although not on Travis, interestingly enough).

In the interest of cleaning out the old issues, I'll just close this and open a new one on Linuxbrew/homebrew-test-bot.

**Comment by sjackman** [comment]
I implemented `HOMEBREW_VERBOSE_USING_DOTS` for `brew uses`.
