### ISSUE TITLE
openssl: ../util/domd: makedepend: not found

### ISSUE THREAD

**Issue by sugaroverflow** [Linuxbrew/legacy-linuxbrew#944]
- [x] Ran `brew update` and retried your prior step? 
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Build failures for ```brew install mysql``` and ```brew install phantomjs``` and ```brew install git```.
(```brew install zlib sqlite tree unzip``` all installed successfully.)

It looks like anything with a dependency of openssl fails with the same error?
See https://gist.github.com/SugarOverflow/266e7f959fcee86dbee1

From the gist:
```make
depend

making depend in crypto...
make[1]: Entering directory `/tmp/openssl20160316-13567-1vpc43l/openssl-1.0.2g/crypto'
../util/domd: 31: ../util/domd: makedepend: not found
mv: cannot stat 'Makefile.new': No such file or directory
make[1]: *** [local_depend] Error 127
make[1]: Leaving directory `/tmp/openssl20160316-13567-1vpc43l/openssl-1.0.2g/crypto'
make: *** [depend] Error 1
```

**Comment by rwhogg** [comment]
It's kind of weird that `openssl` is complaining that `makedepend` is missing...

```
$ ag "makedepend"
openssl.rb
29:  depends_on "makedepend" => :build
```

**Comment by sjackman** [comment]
Please report `brew gist-logs openssl`

**Comment by dendraya** [comment]
what solved the problem in my case was: 
```
brew reinstall makedepend -s
brew reinstall openssl -s
```

**Comment by sjackman** [comment]
Thanks for the workaround, @dendraya.

**Comment by panushri25** [comment]
The think the issue still persists. Tried what @dendraya suggested.
