### ISSUE TITLE
nmap fails to install on uberspace

### ISSUE THREAD

**Issue by phime42** [Linuxbrew/legacy-linuxbrew#945]
Hello,
I try to install nmap using `brew install nmap`, which results in: 

```
$ brew install nmap
==> Downloading https://nmap.org/dist/nmap-7.01.tar.bz2
######################################################################## 100.0%
tar: Child died with signal 11
tar: Error is not recoverable: exiting now
Error: Failure while executing: tar xf /home/mp6/.cache/Homebrew/nmap-7.01.tar.bz2

$ brew gist-logs nmap
Error: No logs.
```

Any ideas?

Thank you so much for your help.

**Comment by rwhogg** [comment]
Signal 11 means `tar` segfaulted. Not sure why.

Can you provide the output of `tar --version` please? Maybe there's a bug in the version of `tar` you're using.

Additionally, can you try to manually execute `tar xf /home/mp6/.cache/Homebrew/nmap-7.01.tar.bz2` to see if it segfaults consistently?

Thanks!

**Comment by sjackman** [comment]
Please report `brew config` and `brew doctor`. These are usually included in `brew gist-logs`, but that clearly didn't work this time. You could try `brew install gnu-tar bzip2 nmap`.
