### ISSUE TITLE
test-bot: Do not uninstall dependencies of gcc

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/legacy-linuxbrew#998]
https://travis-ci.org/Linuxbrew/linuxbrew/builds/119319297#L1551-L1553

```
cc -c -O3 -Wall -DBSD -I. -Ibzip2 -DUNIX   crc32.c
/home/travis/build/Linuxbrew/linuxbrew/Cellar/gcc/5.3.0/bin/../libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/cc1: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
make[1]: *** [unzip.o] Error 1
```

**Comment by sjackman** [comment]
This error is strange. `gcc` *does* currently depend on `zlib`, and `zlib` provides `libz.so.1`. So why this error message?

**Comment by sjackman** [comment]
`zlib` was uninstalled after `libpng`: https://travis-ci.org/Linuxbrew/linuxbrew/builds/119319297#L1213
``
==> brew uninstall --force libpng
Uninstalling libpng... (17 files, 1.2M)
==> PASSED
brew.uninstall.20
==> brew uninstall --force xz zlib
```
This bug is a `brew test-bot` bug that affects the dependencies of `gcc`.

**Comment by rwhogg** [comment]
@sjackman I think you resolved this issue recently?

**Comment by sjackman** [comment]
Yes, resolved by `brew install gcc` before `brew test-bot` which protects it and its dependencies from removal.
